### PR TITLE
Fix Android crash when reloading JSC runtime

### LINKED ISSUE #3351: Crash on app reload on Android in `reanimated::NativeProxy::~NativeProxy`
## Description

When reloading an app in dev mode on Android it causes the following native crash:

```
07-02 17:33:16.550 31265 31407 F libc    : Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x79cfe2f470 in tid 31407 (mqt_native_modu), pid 31265 (com.th3rdwave)
07-02 17:33:16.663 31480 31480 E DEBUG   : failed to read /proc/uptime: Permission denied
07-02 17:33:16.979 31480 31480 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-02 17:33:16.979 31480 31480 F DEBUG   : Build fingerprint: 'google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.211012.001/7818354:userdebug/dev-keys'
07-02 17:33:16.979 31480 31480 F DEBUG   : Revision: '0'
07-02 17:33:16.979 31480 31480 F DEBUG   : ABI: 'arm64'
07-02 17:33:16.979 31480 31480 F DEBUG   : Timestamp: 2022-07-02 17:33:16.663304043-0400
07-02 17:33:16.979 31480 31480 F DEBUG   : Process uptime: 0s
07-02 17:33:16.979 31480 31480 F DEBUG   : Cmdline: com.th3rdwave
07-02 17:33:16.979 31480 31480 F DEBUG   : pid: 31265, tid: 31407, name: mqt_native_modu  >>> com.th3rdwave <<<
07-02 17:33:16.979 31480 31480 F DEBUG   : uid: 10158
07-02 17:33:16.979 31480 31480 F DEBUG   : tagged_addr_ctrl: 0000000000000001
07-02 17:33:16.979 31480 31480 F DEBUG   : signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x79cfe2f470
07-02 17:33:16.979 31480 31480 F DEBUG   :     x0  0000000000000000  x1  00000079b55d3cb0  x2  b400007ac6524368  x3  0000000000000000
07-02 17:33:16.979 31480 31480 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000000
07-02 17:33:16.979 31480 31480 F DEBUG   :     x8  0000000000000000  x9  89d2bbb4d830c3c8  x10 0000000000000000  x11 00000079cfe256a4
07-02 17:33:16.979 31480 31480 F DEBUG   :     x12 00000079b55d0f58  x13 0000000000000010  x14 0000000000080100  x15 00000000ebad6a89
07-02 17:33:16.979 31480 31480 F DEBUG   :     x16 00000079d00af7a0  x17 0000007d0ff9c9e8  x18 000000799c7a4000  x19 b400007ab66008f0
07-02 17:33:16.979 31480 31480 F DEBUG   :     x20 00000079b55d4000  x21 b400007ab66008f0  x22 0000000014ae25c8  x23 000000000000106e
07-02 17:33:16.979 31480 31480 F DEBUG   :     x24 0000007a63c08d00  x25 00000079b55d2470  x26 00000079b55d2478  x27 00000079b55d2470
07-02 17:33:16.979 31480 31480 F DEBUG   :     x28 00000079b55d2340  x29 00000079b55d21d0
07-02 17:33:16.979 31480 31480 F DEBUG   :     lr  00000079cfe2f420  sp  00000079b55d2180  pc  00000079cfe2f470  pst 0000000060001000
07-02 17:33:16.979 31480 31480 F DEBUG   : backtrace:
07-02 17:33:16.979 31480 31480 F DEBUG   :       #00 pc 00000000003e1470  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libhermes-executor-debug.so (BuildId: 0a41b90f49e9d955)
07-02 17:33:16.979 31480 31480 F DEBUG   :       #01 pc 00000000003e134c  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libhermes-executor-debug.so (BuildId: 0a41b90f49e9d955)
07-02 17:33:16.979 31480 31480 F DEBUG   :       #02 pc 00000000003e12f8  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libhermes-executor-debug.so (BuildId: 0a41b90f49e9d955)
07-02 17:33:16.979 31480 31480 F DEBUG   :       #03 pc 00000000003d76d8  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libhermes-executor-debug.so (BuildId: 0a41b90f49e9d955)
07-02 17:33:16.979 31480 31480 F DEBUG   :       #04 pc 000000000014aa18  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libreanimated.so (reanimated::NativeProxy::~NativeProxy()+72) (BuildId: 1342bf55e148097f5c6ad39600602e1edc594a73)
07-02 17:33:16.979 31480 31480 F DEBUG   :       #05 pc 000000000014abb0  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libreanimated.so (reanimated::NativeProxy::~NativeProxy()+36) (BuildId: 1342bf55e148097f5c6ad39600602e1edc594a73)
07-02 17:33:16.979 31480 31480 F DEBUG   :       #06 pc 000000000001eaa0  /data/app/~~2g7FZdCNUmQDIefm1h6MZA==/com.th3rdwave-djBIBaiQa6xbQpQ4pX35Rw==/lib/arm64/libfbjni.so (BuildId: 27496b9e5551bff5c79496b936b663bf8868c68b)
```

Seems to be caused by https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/cpp/NativeProxy.cpp#L70. Removing those line prevents the crash.

Not sure if there is anything special needed to repro the crash, note this is using hermes.

### Expected behavior

No crash

### Actual behavior & steps to reproduce

Reload the app in dev mode.

## Snack or minimal code example

N/A

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    main (e5c5dcd9e26e9443f59864d9763b049e0bda98e7)     |
| react-native-reanimated              |    3.0.0-rc.0     |
| NodeJS                               |         |
| Xcode                                |         |
| Java                                 |   11      |
| Gradle                               |   7.4.2      |
| expo                                 |         |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

### PR DESCRIPTION
**Pull request by tomekzaw**
## Description

Fixes #3351.

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Review by lukmccall — APPROVED** [review]
I've tested it in the expo go and seems to be working fine 🔥

**Comment by tomekzaw** [comment]
@piaskowyk Can we get this fix in 2.10 release?

**Review by piaskowyk — APPROVED** [review]

**Comment by Slapbox** [comment]
Was this incorporated into 2.10.0? I think yes? But I don't see if in the changelog or in the compare feature: https://github.com/software-mansion/react-native-reanimated/compare/2.9.1...2.10.0

This crash is killing us.

**Comment by tomekzaw** [comment]
Hey, it looks like this was released only in 3.0.0-rc.2. @piaskowyk Can we get this cherry-picked for 2.11?

**Comment by Slapbox** [comment]
Confirming the crash appears to be resolved now.

**Pull request merged**
