### PR TITLE
Update initial style every render

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

We can't use just initial style as the default style in every render because these styles can be outdated. We can't change the default style after the first render, because after the second render we don't run mapper that's why the component can change the style to the initial value.

Related:
- https://github.com/software-mansion/react-native-reanimated/pull/2580
- https://github.com/software-mansion/react-native-reanimated/pull/2431
- https://github.com/software-mansion/react-native-reanimated/issues/2406
- https://github.com/software-mansion/react-native-reanimated/pull/1470

### code

Before

https://user-images.githubusercontent.com/36106620/158142874-a11191e7-c0d9-4c3f-8f18-e5b540a6f17c.mov

https://user-images.githubusercontent.com/36106620/158167177-81dfa334-db01-4e04-a234-e1069e8d715b.mov

After

https://user-images.githubusercontent.com/36106620/149799832-b0c0748d-2d9d-42b9-b9ba-f6492cc1fbf0.mov

<details>
<summary>code</summary>

```js
import Animated, {
  useSharedValue,
  withTiming,
  useAnimatedStyle,
  Easing,
} from 'react-native-reanimated';
import { View, Button } from 'react-native';
import React, { useState } from 'react';

export default function AnimatedStyleUpdateExample(props:any) {
  const randomWidth = useSharedValue(10);

  const [counter, setCounter] = useState(0);
  const [counter2, setCounter2] = useState(0);
  const [itemList, setItemList] = useState([]);
  const [toggleState, setToggleState] = useState(false);

  const config = {
    duration: 500,
    easing: Easing.bezier(0.5, 0.01, 0, 1),
  };

  const style = useAnimatedStyle(() => {
    return {
      width: withTiming(randomWidth.value, config),
    };
  });

  const staticObject = <Animated.View
    style={[
      { width: 100, height: 3, backgroundColor: 'black', margin: 1 },
      style,
    ]}
  />

  const renderItems = () => {
    let output = []
    for(let i = 0; i < counter; i++) {
      output.push(
        <Animated.View
        key={i + 'a'}
          style={[
            { width: 100, height: 3, backgroundColor: 'blue', margin: 1 },
            style,
          ]}
        />
      )
    }
    return output
  }

  return (
    <View
      style={{
        flex: 1,
        flexDirection: 'column',
        marginTop: 30
      }}>
      <Button
        title="animate"
        onPress={() => {
          randomWidth.value = Math.random() * 350;
        }}
      />
      <Button
        title="increment counter"
        onPress={() => {
          setCounter(counter + 1)
        }}
      />
      <Button
        title="add item to static lists"
        onPress={() => {
          setCounter2(counter2 + 1)
          setItemList([...itemList, <Animated.View
            key={counter2 + 'b'}
            style={[
              { width: 100, height: 3, backgroundColor: 'green', margin: 1 },
              style,
            ]}
          />])
        }}
      />
      <Button
        title="toggle state"
        onPress={() => {
          setToggleState(!toggleState)
        }}
      />
      <Animated.View
        style={[
          { width: 100, height: 3, backgroundColor: 'orange', margin: 1 },
          style,
        ]}
      />
      {toggleState && <Animated.View
        style={[
          { width: 100, height: 3, backgroundColor: 'black', margin: 1 },
          style,
        ]}
      />}
      {toggleState && staticObject}
      {renderItems()}
      {itemList}
    </View>
  );
}

```

</details>

### code2

Still works

https://user-images.githubusercontent.com/36106620/149800303-4c4316aa-7765-4c66-a81a-74489d9f0215.mov

<details>
<summary>code2</summary>

```js
import React from 'react';
import { View } from 'react-native';
import Animated, {
  useSharedValue,
  withSpring,
  useAnimatedStyle,
  useAnimatedGestureHandler,
  interpolate,
  Extrapolate,
  runOnJS,
} from 'react-native-reanimated';
import {
  PanGestureHandler,
  PanGestureHandlerGestureEvent,
} from 'react-native-gesture-handler';
import { useEffect, useState } from 'react';

function DragAndSnap(): React.ReactElement {
  const translation = {
    x: useSharedValue(0),
    y: useSharedValue(0),
  };
  type AnimatedGHContext = {
    startX: number;
    startY: number;
  };

  // run a couple of updates when gesture starts
  const [counter, setCounter] = useState(0);
  const makeFewUpdates = () => {
    let countdown = 100;
    const doStuff = () => {
      setCounter(countdown);
      countdown--;
      if (countdown > 0) {
        requestAnimationFrame(doStuff);
      }
    };
    doStuff();
  };

  const gestureHandler = useAnimatedGestureHandler<
    PanGestureHandlerGestureEvent,
    AnimatedGHContext
  >({
    onStart: (_, ctx) => {
      ctx.startX = translation.x.value;
      ctx.startY = translation.y.value;
      runOnJS(makeFewUpdates)();
    },
    onActive: (event, ctx) => {
      translation.x.value = ctx.startX + event.translationX;
      translation.y.value = ctx.startY + event.translationY;
    },
    onEnd: (_) => {
      translation.x.value = withSpring(0);
      translation.y.value = withSpring(0);
    },
  });

  const stylez = useAnimatedStyle(() => {
    const H = Math.round(
      interpolate(translation.x.value, [0, 300], [0, 360], Extrapolate.CLAMP)
    );
    const S = Math.round(
      interpolate(translation.y.value, [0, 500], [100, 50], Extrapolate.CLAMP)
    );
    const backgroundColor = `hsl(${H},${S}%,50%)`;
    return {
      transform: [
        {
          translateX: translation.x.value,
        },
        {
          translateY: translation.y.value,
        },
      ],
      backgroundColor,
    };
  });

  // make render slower
  let f = 0;
  for (var i = 0; i < 1e8; i++) {
    f++;
  }

  return (
    <View style={{ flex: 1, margin: 50 }}>
      <PanGestureHandler onGestureEvent={gestureHandler}>
        <Animated.View
          style={[
            {
              width: 40,
              height: 40,
            },
            stylez,
          ]}
        />
      </PanGestureHandler>
    </View>
  );
}

export default DragAndSnap;

```

</details>

### CODE REVIEW

**Comment by hirbod** [comment]
This PR is what I was searching for. It fixes plenty of issues for me, specially with react-native-bottom-sheet.
Hopefully this is going to land quickly.

**Comment by daavidkllr** [comment]
Same here, this will fix a bunch of bugs a bunch of bugs I've investigated.
Please do not let us wait too long for this 🙂

**Comment by piaskowyk** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/2580 was merged, so I can deal with this now.

**Comment by piaskowyk** [comment]
I want to release these changes in 2.5.0

**Comment by hirbod** [comment]
@piaskowyk when do you think 2.5.0 will be out? We're desperately waiting for this PR to land.
This is really needed for a bunch of libs to work correctly

**Comment by piaskowyk** [comment]
@hirbod I worked on this issue, and I discovered a serious problem with the order of mapper execution. In other words, there is a possibility to perform updates on not fully rendered components. I've been talking to @kmagiera bout this PR and we decided that this is just a fix of effect not a source of the problem. Even if I release these changes it can be harmful in some cases, and we don't want to add regression. So we decided to fix it on the native side. I have some unpublished prototypes but I need some time to polish them. At this moment I am only one maintainer of reanimated so that's why it's taking so long - sorry for that.

**Comment by hirbod** [comment]
@piaskowyk thank you very much for the update. I understand your concerns. Personally speaking, I haven't had any regressions so far but good thing that you've catched them (I am on 2.3.1 and using a patch-file to add your changes), and it fixes bunch of issues with bottom-sheet and moti for me. As you can see, there are plenty of issues linking to this here and the operations order issue. 

So I will stick with the patch for now and hope that those native fixes will tackle this issues down.
If I can help you out with testing, give me a shout!

**Comment by hirbod** [comment]
@piaskowyk I can also confirm regressions now. So good thing that you've catched it.

**Comment by piaskowyk** [comment]
@hirbod I found an easier solution, could you check if it works for you?

**Comment by piaskowyk** [comment]
@hirbod I found an easier solution, could you check if it works for you?

**Comment by hirbod** [comment]
@piaskowyk shall I install `@piaskowyk/initial-style-shared` or this PR directly?

**Comment by hirbod** [comment]
@piaskowyk all of my tests ands bugs with react-native-bottom-sheet, react-native-vision-camera and moti are gone. The regressions I've encountered are gone as well.

From my end, this PR looks rock solid!

**Comment by piaskowyk** [comment]
Thanks for the help <3

**Review by tomekzaw — APPROVED** [review]

**Comment by tr3v3r** [comment]
@tomekzaw hi! Just writing to enquire when the release with this update is planned? Thanks

**Comment by tomekzaw** [comment]
@tr3v3r We plan to release 2.5.0 on Monday. In the meantime, you can try out [this](https://github.com/software-mansion/react-native-reanimated/actions/runs/2004710154) version built on our CI.

**Pull request merged**
