### PR TITLE
Get rid of <AnimatedLayout/> 

### PR DESCRIPTION
**Pull request by Szymon20000**
Co-authored-by @piaskowyk 
## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]

**Comment by happyfloat** [comment]
Well done! Anything else needs to be done or can this be released as the new alpha? :)

**Comment by piaskowyk** [comment]
@happyfloat This week Wednesday/Thursday 🚀

**Comment by andrewdang17** [comment]
Since this was removed, what is the alternative?

**Comment by tarvy** [comment]
Any word on the alternative to this? still haven't heard anything and it's not clear from the documentation.

**Comment by ashleyww93** [comment]
@tarvy @andrewdang17 I also came to this PR looking for an alternative.

I'm not sure what we **should** be using, but `Animated.View` worked for my needs.

**Comment by josecervino** [comment]
`Animated.View` with a `.delay()` on layout props works in case you're looking for sequential, staggered list animations.

Just pass in the index of the item during a loop to calculate against
```
<Animated.View entering={FadeInDown.delay(index * 100)}>
    {props.children}
</Animated.View>
```

You can also add `Layout.springify()` to the layout prop for list-reactivity to list element changes
```
<Animated.View entering={FadeInDown.delay(index * 100)} layout={Layout.springify()}>
    {props.children}
</Animated.View>
```

Here's the relevant documentation: 
- https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/entryAnimations
- https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/exitAnimations
- https://docs.swmansion.com/react-native-reanimated/docs/api/LayoutAnimations/layoutTransitions

**Comment by wmonecke** [comment]
Hey guys I am a bit lost here...

I am trying to fade-in/ fade-out stuff when the api call is successful.

How do we transition between these two states seamlessly in v3?

AnimatedLayout got removed so I am still trying to hack my way through this one.

**Pull request merged**
