### PR TITLE
Remove cspell.json

### PR DESCRIPTION
**Pull request by piaskowyk**
## Summary

We no longer need this file since we have removed the c-spell CI.

### CODE REVIEW

**Review by szydlovsky — APPROVED** [review]

**Review by tjzel — CHANGES_REQUESTED** [review]
We use this for precommit now 🙈

**Comment by piaskowyk** [comment]
But where? I can see any usage of cspell in our codebase 🤔

**Review by tomekzaw — APPROVED** [review]
Goodbye cspell.json

**Comment by tjzel** [comment]
Seems like it got lost between
- #5991


and 

- #5998

**Comment by piaskowyk** [comment]
Let it gooo! - https://youtu.be/moSFlvxnbgk?si=myG1cWOvhBwovvlP&t=60

**Review by tjzel — APPROVED** [review]

**Pull request merged**
