### PR TITLE
Apply `object-shorthand` eslint rule

### PR DESCRIPTION
**Pull request by Latropos**
## Summary
I was able to do this changes automatically, and then I've reviewed them to be sure nothing was broken.

This PR should me merged after eslint update: https://github.com/software-mansion/react-native-reanimated/pull/5594

### CODE REVIEW

**Review by tomekzaw — APPROVED** [review]
Thanks for this atomic and quite necessary PR. Well done!

**Review by tjzel — APPROVED** [review]
`callback: callback` I will miss you 😭

**Review by piaskowyk — APPROVED** [review]

**Comment by tomekzaw** [comment]
I believe this PR is ready to be merged, what are we waiting for?

**Comment by tjzel** [comment]
@tomekzaw

> This PR should me merged after eslint update: https://github.com/software-mansion/react-native-reanimated/pull/5594

**Pull request merged**
