### PR TITLE
[Reanimated + Screens] Shared Element Transition

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

Shared Element Transition based on Reanimated + Screens

## API
```js
```

## TODO
- [ ] //

## Roadmap
- Animation for all styles
- Animation with navigation header
- Screen transition navigation

Related PR to Screens: https://github.com/software-mansion/react-native-screens/pull/1591

Co-authored-by: @piaskowyk @WoLewicki

### CODE REVIEW

**Comment by nandorojo** [comment]
Hey @piaskowyk! Just wondering if there is progress planned for shared transitions :)

Let me know if there's anything I can do to help. Maybe to start it could just support iOS to make it easier?

I think there are two kinds of SETs:

1. Transition between screens (more complicated)
2. Transitions on a given screen

It may be easier to start with 2, where transitions of elements work inside a given screen. I envision that the API could use a `layoutId` prop, borrowed from `framer-motion`'s shared layout transitions.

By default, one component with a given [`layoutId`](https://www.framer.com/docs/layout-group/#namespace-layoutid) can be rendered at a time. This would work like `key` does now, except that it would work _across_ components. Currently, the Reanimated implementation uses `key`, which restricts you to only doing shared transitions of siblings.

I'd like to propose the framer API:

```tsx
const Item = ({ selected }) => {
  return <View>{selected && <Animated.View layoutId="indicator" />}</View>
}


const List = ({ selectedId }) => items.map(id => <Item key={id} selected={selectedId === id} />)
```

In this case, if the component with the `layoutId` prop changes, it transitions from one to the next.

By default, `layoutId` is global. However, it can also be wrapped with a [`LayoutGroup`](https://www.framer.com/docs/layout-group/):

```tsx
const List = ({ selectedId }) => <LayoutGroup>{items.map(id => <Item key={id} selected={selectedId === id} />}</LayoutGroup>
```

**Comment by haibert** [comment]
Hey guys,

Just curious, has this idea been completely abandoned or just put aside for the time being ?

**Comment by haibert** [comment]
@piaskowyk Awesome! Cant wait 🥳

**Comment by haibert** [comment]
**This is too exciting.**

**Comment by enesozturk** [comment]
Any update on this? Looking forward to trying different page transition examples! @piaskowyk

**Comment by piaskowyk** [comment]
@enesozturk I will share the examples, but the last time we were focused on Ranimated stability improvements, that's why I was inactive in this PR, but I will back to this one soon.

**Comment by nandorojo** [comment]
love seeing all the progress on this!! 👀

**Comment by piaskowyk** [comment]
Currently we are waiting for https://github.com/software-mansion/react-native-reanimated/pull/3332 PR.

**Comment by piaskowyk** [comment]
Closed due to: https://github.com/software-mansion/react-native-reanimated/pull/3827

**Comment by haibert** [comment]
> Closed due to: https://github.com/software-mansion/react-native-reanimated/pull/3827

Wait 🥺 meaning this won't be implemented anymore ?

**Comment by nelsonprsousa** [comment]
> > Closed due to: #3827
> 
> Wait 🥺 meaning this won't be implemented anymore ?

There's a new PR, you can check the description:

Successor of: https://github.com/software-mansion/react-native-reanimated/pull/2561

**Pull request closed without merging**
