### PR TITLE
fix: dependency downloads on v2

### LINKED ISSUE #3523: Why 2.10.0 need to download and build boost, glog, double-conversion, folly when newArchEnabled is set to false
### Description

Why 2.10.0 need to download and build boost, glog, double-conversion, folly when newArchEnabled is set to false?

even if newArchEnabled = true, it should use the react-native one

image

### Steps to reproduce

1. create a react native app
2. add react-native-reanimated: "^2.10.0" to package
3. yarn android

### Snack or a link to a repository

/

### Reanimated version

2.10.0

### React Native version

0.69.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

_No response_

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by kkafar**
## Description

Fixes #3523 on v2

Fix for v3 comes with #3588 

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by Aravindmuniraj** [comment]
react-native-downlaod boost takes more than1 hour in gradle build and failing, anything we can fo this ?

**Comment by kkafar** [comment]
Hi @Aravindmuniraj, if you are building `reanimated@v2` from sources these libraries must be downloaded (see [here](https://github.com/software-mansion/react-native-reanimated/issues/3523#issuecomment-1230902722) for explanation).

However if you are not building from source these should not be downloaded (and I believe they are not, as this was fixed with #3672 -- if some invalid behaviour still appears please file a new issue (and maybe tag me there)).

Download time of this libraries is highly connection speed dependent and there can not be done much on the library side. 

I'm closing this PR, because as I mentioned earlier the issue was solved with #3672.

**Comment by varshith5c** [comment]
Hey I am still getting to download - downloadBoost
Gradle version: 7.5.1
Android gradle plugin: 7.2.1
react-native: 0.70.6

**Comment by kkafar** [comment]
@varshith5c, Reanimated 3 is builded from source ([here's why](https://github.com/software-mansion/react-native-reanimated/issues/2650#issuecomment-1592781138)) -- the libraries must be downloaded.

**Pull request closed without merging**
