### PR TITLE
Pass down generator boolean in babel plugin

### LINKED ISSUE #5564: Generator asterisk not preserved in the babel plugin
### Description

The following:
```ts
function* simpleGenerator() {
  "worklet";
  yield "Hello";
  yield "World";
}
```

generates to:
```ts
function simpleGenerator() {
  yield "Hello";
  yield "World";
}
```

which is invalid

### Steps to reproduce

simply add the following function to your reanimated project:
```ts
function* simpleGenerator() {
  "worklet";
  yield "Hello";
  yield "World";
}
```

### Snack or a link to a repository

I recommend the try the steps above

### Reanimated version

latest

### React Native version

latest

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #5564

### CODE REVIEW

**Comment by wcandillon** [comment]
closing since the story is much bigger than this.

**Comment by wcandillon** [comment]
As far as I tested, this PR is enough to have full generator support with worklets which I'm quite excited about.

**Review by tomekzaw — COMMENTED** [review]
Thanks for the PR! Could you also please add a short unit/shapshot test?

cc @tjzel

**Comment by wcandillon** [comment]
if you give me some pointer on how to do it, I'd be happy to.

**Comment by tomekzaw** [comment]
You can just paste some input source code that doesn't work without this change and we'll take care of it!

**Comment by wcandillon** [comment]
@tomekzaw I added a little test ☺️

**Review by tomekzaw — APPROVED** [review]
Perfect, thanks! Awaiting final approval from @tjzel

**Review by piaskowyk — APPROVED** [review]

**Comment by tjzel** [comment]
Everything looks good, I just added one more test 😺

**Comment by colinta** [comment]
I'm really excited for this – @wcandillon and I were exploring using generators as a more fluent way to compose functions that need to call out to a runtime, and realized that it was especially well suited to animation code! 🥳

**Pull request merged**
