### PR TITLE
remove initialUpdaterRun from useAnimatedStyle

### PR DESCRIPTION
**Pull request by karol-bisztyga**
## Description

Removed `initialUpdaterRun` from `useAnimatedStyle` hook.

### CODE REVIEW

**Comment by karol-bisztyga** [comment]
@kmagiera I have mentioned this problem before. I don't think this is the best design because it causes the callback passed to the hook to be called on the JS thread. Plus it is not necessary as the mapper launches that callback right away anyway. Apparently this caused the code from linked issue to not work(thus could be considered error prone). I don't see a scenario when getting rid of that initial updater breaks anything. If there is one, let's see it. Marked as a draft as there might be some further changes required to increase gracefulness of handling the case.

**Comment by karol-bisztyga** [comment]
With that being said I understand that the author of that issue came up with some kind of workaround, however I think we should aim at handling as much ways of writing the code as possible.

**Comment by kmagiera** [comment]
And example is when you have any layout related prop placed in the animated style.

Layout props cannot be immediately set on the UI thread because layout runs on a separate thread. If we skip that layout prop here the initial layout is going to be calculated as if the property wasn't there, and only after a frame of delay we'd get a proper layout updated. This will cause view flickering right after mounting.

**Comment by kmagiera** [comment]
I don't see any issue linked in the description. There is just a reverse link in #1062 so I'm assuming you are talking about that issue then? If so I don't see how removing initial run fixes that problem. The problem in #1062 is that animation helpers don't yet support types other than numbers. It appears that we are able to process the rotation param internally, but this is inconsistent with the way react-native expects that parameters to be defined. I'd prefer to keep it consistent and if react-native does not allow numbers for rotation we shouldn't too

**Comment by karol-bisztyga** [comment]
I understand. I still think this initial call could be removed(talking about that frame delay). As I get it we are talking about something like this:
```
const Comp = () => {
	const widthSv = useSharedValue(200)
	const uas = useAnimatedStyle=(() => {
		return {
			width: widthSV.value
		}
	})
	return (
		<Animated.View style={[{ width:10, height: 10, backgroundColor: 'red' }, uas]} />
	)
}
```
So here the problem is here will be that frame-delay between the initial value of `10` and the value of `200` which would be set later on the UI thread.

I just think the users should be aware of that and such code would be some kind of bad practice which should be avoided. So it would require specifying some pre defined default styles manually but there would be only one place where the styles from the callback would be set.

**Comment by Johan-dutoit** [comment]
@kmagiera to clarify #1062 a bit more (if it helps with this or not, I don't know), is that I couldn't use the result of `withTiming` directly to do the rotation i.e. `${withTiming(45)}deg`.  This could be incorrect usage, maybe it should be `${withTiming(45).value}deg`, which I hadn't tried as the return type for `withTiming` is number.

What did eventually work, was creating a new derived value that returned the `withTiming` result i.e. `${derivedValue.value}deg`

**Comment by terrysahaidak** [comment]
> @kmagiera to clarify #1062 a bit more (if it helps with this or not, I don't know), is that I couldn't use the result of `withTiming` directly to do the rotation i.e. `${withTiming(45)}deg`.  This could be incorrect usage, maybe it should be `${withTiming(45).value}deg`, which I hadn't tried as the return type for `withTiming` is number.
> 
> What did eventually work, was creating a new derived value that returned the `withTiming` result i.e. `${derivedValue.value}deg`

Both cases won't work because there will be no way to tell the core to which property the animation is assigned.

**Pull request closed without merging**
