### PR TITLE
fix: Only inject `global.performance.now` if not already defined

### PR DESCRIPTION
**Pull request by mrousavy**
Alternative solution to #2761, related: #2760

### CODE REVIEW

**Comment by mrousavy** [comment]
cc @michaelknoch

**Comment by mrousavy** [comment]
sorry for not dropping a detailed description - but basically with this approach the outer if isn't too confusing, and it also provides the possibility of having `global.performance` natively injected in the future (assuming that's where RN is heading, with JSI) cc @piaskowyk

**Review by piaskowyk — APPROVED** [review]
Reasonable changes 🚀

**Comment by nandorojo** [comment]
This fixed remote debugging for me, thanks!

**Comment by daxaxelrod** [comment]
Holy macaroni salad thanks a ton. Redux for flipper still needs work and it's awesome to get react-native-debugger back

**Pull request merged**
