### PR TITLE
ADD interpolateColors to jest mock 

### PR DESCRIPTION
**Pull request by YOEL311**
## Changes

solve #2749  issue

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by orazoulay** [comment]
thanx

**Comment by adirpion** [comment]
Thanks.

**Comment by avielyoeff** [comment]
thanks

**Comment by idandamri** [comment]
thanks!

**Review by piaskowyk — APPROVED** [review]

**Pull request merged**
