### PR TITLE
Remove explicit CMake version

### LINKED ISSUE #3513: CircleCI failed due to react-native-reanimated (android)
### Description

Circle CI lane failed at react-native-reanimated in android

log added

```Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :react-native-reanimated
Native libs debug enabled: false
Android gradle plugin: 7.0.3
Gradle: 7.3
building Reanimated2
Checking the license for package NDK (Side by side) 21.4.7075529 in /opt/android/sdk/licenses
License for package NDK (Side by side) 21.4.7075529 accepted.
Preparing "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)".
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" ready.
Installing NDK (Side by side) 21.4.7075529 in /opt/android/sdk/ndk/21.4.7075529
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" complete.
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" finished.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> [CXX1300] CMake '3.18.1' was not found in SDK, PATH, or by cmake.dir property.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Steps to reproduce

Run CircleCI lane in reactnative for android 

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.10.0

### React Native version

0.68.0

### Platforms

Android

### JavaScript runtime

_No response_

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

_No response_

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by tomekzaw**
## Description

Fixes #3513 and #3516.

✅  It works with CMake 3.10.2.

❌  It doesn't work with CMake 3.6.0 because `CXX_STANDARD 17` is available since 3.8 ([source](https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html))

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Review by wkozyra95 — APPROVED** [review]

**Review by piaskowyk — APPROVED** [review]

**Comment by Smatched** [comment]
There is no new nom version with this fixed, right? Current 2.10.0 still seems to have this explicit version set, which leads to multiple pipelines failing. Can we get a new version out for this one?

**Comment by tomekzaw** [comment]
@Smatched Yes, we plan to release 2.11 next week.

**Comment by dylmye** [comment]
Hey, is there any update to the 2.11 release please? :)

**Comment by tomekzaw** [comment]
@dylmye We still have some PRs left to merge before releasing 2.11 so fingers crossed it's gonna be this week 🤞

**Comment by dylmye** [comment]
Seems like 2.11 has been released [on npm](https://www.npmjs.com/package/react-native-reanimated/v/2.11.0), just not tagged on GitHub @SudoPlz

**Pull request merged**
