### PR TITLE
Remove reference to deprecated "compile" configuration for compatibility with Gradle 7

### LINKED ISSUE #3119: v1.13.4 fails to build with Gradle 7
## Description

Despite #2881, v1.13.4 is still incompatible with Gradle 7. Gradle 7 removed "compile" in favor of "implementation," and the `android/build.gradle` file is still using `compile` in the context of

```
task androidJavadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += files(android.bootClasspath)
    classpath += files(project.getConfigurations().getByName('compile').asList())
    include '**/*.java'
}
```

which results in the error `Configuration with name 'compile' not found.`

### Expected behavior

Projects using the latest v1 of `react-native-reanimated` can build with Gradle 7.

### Actual behavior & steps to reproduce

Updating to Gradle 7 fails to build `react-native-reanimated` with `Configuration with name 'compile' not found.`, specifically pointing at the `files(project.getConfigurations().getByName('compile').asList())` line.

Alternate simple repro steps:
1. Use `npx react-native init` to create a new React Native app
2. `yarn add react-native-reanimated@1.13.4`
3. `yarn android`

## Snack or minimal code example

https://github.com/TheAlmightyBob/ReanimatedGradle7

(this is simply the result of following the "alternate simple repro steps" above)

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.66.4      |
| react-native-reanimated              |    1.13.4     |
| Java                                 |    11     |
| Gradle                               |    7.1.1 or 7.2     |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

### PR DESCRIPTION
**Pull request by TheAlmightyBob**
## Description

Fixes #3119. 

## Changes

Use `implementation` instead of `compile`. This is the same fix as https://github.com/auth0/react-native-auth0/pull/450.

## Test code and steps to reproduce

Include `react-native-reanimated` with this change in a project using Gradle 7 and it should successfully build.

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]
Thanks! Valuable changes 🎉

**Comment by TheAlmightyBob** [comment]
@piaskowyk Can a new minor v1 release be published with this change? 🙂

**Comment by cjhines** [comment]
@piaskowyk Please publish.

**Comment by jforaker** [comment]
@piaskowyk i will buy you a [coffee](https://ko-fi.com/) if you publish a v1 update with this change  🙏

**Comment by trevor-coleman** [comment]
Would be great to have this published!

**Comment by douglasjunior** [comment]
Guys, I've published in my account, you can use:

```json
   "react-native-reanimated-v1": "1.13.5",
```

Or

```json
   "react-native-reanimated": "npm:react-native-reanimated-v1@1.13.5",
```

**Comment by xchwarze** [comment]
Install dep like this: 
```
		"react-native-reanimated": "https://github.com/TheAlmightyBob/react-native-reanimated#107bf61df76ca08be2231381f92bde54adef0794",

```

**Comment by TheAlmightyBob** [comment]
@xchwarze Why not use the one @douglasjunior published? I do not recommend pointing your project directly at my GitHub fork....

**Comment by xchwarze** [comment]
The commir are merged in Apr 1
so until they do a new release the only thing that makes sense is to use the commit of this repo 
https://github.com/software-mansion/react-native-reanimated/commit/c4a6b6f687ede090f6081064abe83a2ef9a05784

**Comment by douglasjunior** [comment]
The problem with pointing directly to the fork, is that reanimated does a pre-compilation before publishing, I don't know if this can affect anything, so I decided to publish on npm.

**Pull request merged**
