### PR TITLE
Fix bug on release

### PR DESCRIPTION
**Pull request by Latropos**
## Summary
Fix to https://github.com/software-mansion/react-native-reanimated/issues/5067

This fix makes reanimated work in release build

### CODE REVIEW

**Comment by ranaavneet** [comment]
@Latropos this check is already present in 3.5.1 but it still crashes

https://github.com/software-mansion/react-native-reanimated/blob/3.5.1/src/reanimated2/NativeMethods.ts#L65

**Review by tjzel — APPROVED** [review]
👍

**Comment by tjzel** [comment]
Was already done in #5065

**Comment by ranaavneet** [comment]
@tjzel @Latropos is there a separate PR to fix #5067 ?

**Pull request closed without merging**
