### PR TITLE
Add Airbnb-like header example with reanimated v2

### PR DESCRIPTION
**Pull request by valentinoConti**
## Description

I researched everywhere for a way to create an animation on a header, where:
- If I scroll down, the header starts hiding along the scroll until it get completely hidden.
- If I start scrolling up, the header starts to show along the scroll until its visible.

Basically I was trying to get what its shown on [this video](https://www.youtube.com/watch?v=JPx8IlfYQ-c) or on other websites, but using the version 2 of reanimated instead of the version 1.

I tried to use the diffClamp methods along with the interpolateNode but I was having a lot of problems to get that effect working and I was not able to found an example for this with reanimated v2 anywhere on the internet.

I created my own algorithm to achieve that effect and it's working amazing, even better than the ones that I found on internet using v1 because with this, you can activate the 'bounces' prop of the FlatList/ScrollView and use the refresh control and footer component without a problem. so I wanted to contribute with this in case somebody wants to create the same animation for a header.

## Screenshots / GIFs

Simulator Screen Recording - iPhone 12 - 2021-06-08 at 23 40 20

### CODE REVIEW

**Comment by piaskowyk** [comment]
Before merge, we need to resolve this issue: https://github.com/software-mansion/react-native-reanimated/issues/2285

**Comment by valentinoConti** [comment]
> Before merge, we need to resolve this issue: #2285

Fixed!

I'm pretty sure that at the time I created this PR that wasn't happening, the first thing I did was going to the code were that crash happens (on **ios/REANodesManager.m**) and commented it, and it started working fine without crashing:

```
- (BOOL)uiManager:(RCTUIManager *)manager performMountingWithBlock:(RCTUIManagerMountingBlock)block {
  RCTAssert(_mounting == nil, @"Mouting block is expected to not be set");
  _mounting = block;
  return YES;
}
```

But, because I know nothing about native code I did a research to see if I found something else to do, I found this open issue https://github.com/software-mansion/react-native-reanimated/issues/1947 with same problem and used the same fix that they say on the comments, wrap the interpolate on a withTiming with only 10 of duration, works perfectly fine now, but I don't really know if that is the way to go of if there is some issue on the native code used on the reanimated repo

Cheers!

**Comment by piaskowyk** [comment]
Related issue - https://github.com/software-mansion/react-native-reanimated/pull/2681

**Comment by jwajgelt** [comment]
Hi! I really like your example and after the recent changes introduced to shareable values it seems to work great on iOS on the `main` branch.
However, due to differences in how scroll events are handled on iOS and Android, this example doesn't seem to work correctly there, and I couldn't find a way to adapt it to have the same result on both platforms.

If you're still interested in getting this example merged, and have an idea how to fix it on Android, feel free to open a new PR.

**Comment by Linuhusainnk** [comment]
Any examples similar in v3

**Pull request closed without merging**
