### PR TITLE
Add release-it

### PR DESCRIPTION
**Pull request by jakub-gonet**
Adding release-it to make releases easier.
Added a custom check for changes in ios/ and android/ folders, which prevents releasing patches when minor ver. should apply. Unfortunately, release-it doesn't support hook return codes, so it crashes :/
Hopefully, the comment above check is sufficient to know what went wrong.

### CODE REVIEW

**Comment by kmagiera** [comment]
nice! Can you add a description to this PR to document what is the expected output of the check hook and what happens when the check fails?

**Comment by kmagiera** [comment]
^ this is just so that we know what the expected behavior was in case we find issue with it

**Comment by jakub-gonet** [comment]
Ah, my bad, will do.

**Comment by osdnk** [comment]
looks good. Can we merge it? How about making release notes? Is there anything blocking?

**Comment by jakub-gonet** [comment]
Release notes are still made manually, so I didn't configure that. This PR can be merged as soon as it gets approval.

**Pull request merged**
