### PR TITLE
Release 3.5.0 🐎

### PR DESCRIPTION
**Pull request by piaskowyk**
## Summary

Release of 3.5.0 👀 Update package.json

Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/6147177203
Version tester CI: https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/6147184200

### CODE REVIEW

**Comment by efstathiosntonas** [comment]
the world waiting for 3.5.0 to go out:

sad-pablo-lonely

**Comment by efstathiosntonas** [comment]
@software-mansion tean writing the final code lines  prior releasing 3.5.0:

writing-jot

**Comment by piaskowyk** [comment]
With great regret, I must inform you that the release has been postponed to Monday, as we have detected several bugs (on the new architecture/Fabric). We have managed to resolve them, but for the benefit of everyone, we would like to retest these changes before releasing the version. However, tomorrow and Friday, the entire team will be attending the React Native EU conference, so we have decided to reschedule the release date.

**Comment by efstathiosntonas** [comment]
@piaskowyk no worries, just j/k with lot's of love 😄

**Comment by ranaavneet** [comment]
> When will RNR be released? 🥹

Whats RNR?

**Comment by efstathiosntonas** [comment]
> > When will RNR be released? 🥹
> 
> @dohooo what's RNR?

React Native Reanimated

**Review by tomekzaw — APPROVED** [review]
:shipit:

**Review by kacperkapusciak — APPROVED** [review]

**Comment by efstathiosntonas** [comment]
@piaskowyk for some reason there's no changlog on 3.5.0 under the releases page

**Pull request merged**
