### PR TITLE
fix syntax error

### PR DESCRIPTION
**Pull request by lafest**
## Summary

스크린샷 2023-09-22 14 46 10

I met this error in v3.5.4, so fixed syntax error to work well.

### CODE REVIEW

**Comment by tjzel** [comment]
Fix necessary due to user's corrupted `yarn.lock` (#5112 for more context).

**Comment by lafest** [comment]
@tjzel I tried following steps, but yarn did not resolved this issue.
```sh
rm -rf node_modules yarn.lock
yarn cache clean
yarn install
```

Is there any missing steps in my script?

**Comment by lafest** [comment]
How [this line](https://github.com/software-mansion/react-native-reanimated/blob/main/src/reanimated2/threads.ts#L215) in main branch is resolved automatically by yarn?

I think this type error cannot be fixed by yarn.

**Comment by tjzel** [comment]
This is not a type error - `yarn.lock`s tend to get corrupted and then fail to resolve some dependencies properly. Maybe you also need to reset your bundler's cache or something. Try `yarn react-native bundle --reset-cache --platform ios --dev true --entry-file index.js --bundle-output bundle.js`.

**Comment by lafest** [comment]
```sh
rm -rf node_modules yarn.lock
yarn cache clean
yarn install
yarn react-native bundle --reset-cache --platform ios --dev true --entry-file index.js --bundle-output bundle.js
```

this worked well for me. @tjzel thanks for help!
but.. it seems risky that re-install all the yarn.lock file because other unrelative libraries also updated. so, if I find proper dependencies for reanimated, I'll post it.

**Pull request closed without merging**
