### PR TITLE
Android fixes

### PR DESCRIPTION
**Pull request by karol-bisztyga**
## Description

- make liquid swipe example work
- Fix scroll imitation example

### CODE REVIEW

**Review by Szymon20000 — APPROVED** [review]

**Review by jakub-gonet — CHANGES_REQUESTED** [review]
CI fails.

**Comment by karol-bisztyga** [comment]
> CI fails.

I noticed, repairing

**Comment by jakub-gonet** [comment]
@karol-bisztyga, you probably meant 0.10.0 version and not 1.10.0, that's why it's still failing.

**Comment by Szymon20000** [comment]
> @karol-bisztyga, you probably meant 0.10.0 version and not 1.10.0, that's why it's still failing.

0.1.10 actually

**Comment by karol-bisztyga** [comment]
Ok so the problem persisted because I chose non existent version so yarn came up with the prompt which made it work locally but did not change package.json

**Review by Szymon20000 — APPROVED** [review]

**Comment by jakub-gonet** [comment]
Included in #1193.

**Pull request closed without merging**
