### PR TITLE
[Test] test cpplint workflow

### PR DESCRIPTION
**Pull request by mrousavy**
don't merge, don't review.

### CODE REVIEW

**Comment by jakub-gonet** [comment]
[Did it work as intended?](https://github.com/software-mansion/react-native-reanimated/pull/2063/checks?check_run_id=2693561090#step:4:1)

**Comment by mrousavy** [comment]
hmm, it should still be able to report.... 🤔 

Screenshot 2021-05-28 at 12 57 23

**Comment by mrousavy** [comment]
Okay yeah no the GitHub token from reanimated cannot be used since it is being ran on a fork, not the original repo. I believe you can allow running GitHub actions on forks, there must be a setting either in the software-mansion organisation or the reanimated repo.

**Comment by jakub-gonet** [comment]
I'd rather not allow running GH Actions on [untrusted PRs](https://www.infoq.com/news/2021/04/GitHub-actions-cryptomining/) but I think we can enable it if it's possible to only allow running on PRs from previous contributors.

**Pull request closed without merging**
