### PR TITLE
Release 3.13.0

### PR DESCRIPTION
**Pull request by szydlovsky**
## Summary

image

## Test plan

👍

### CODE REVIEW

**Review by tjzel — APPROVED** [review]
🇹🇩

**Comment by efstathiosntonas** [comment]
Untitled

**Comment by szydlovsky** [comment]
@efstathiosntonas ran into some issues while testing the release, we hope to have them addressed tomorrow 😄

**Comment by efstathiosntonas** [comment]
thanks for the heads up @szydlovsky! I'm always joking like that on release PRs 😄 

thank you for your hard work as always!

**Comment by tjzel** [comment]
@efstathiosntonas I laughed hard 😆

**Pull request merged**
