### PR TITLE
Reanimated 2.5.0 type check fix

### PR DESCRIPTION
**Pull request by scyrych**
## Description

Importing types like this `export type TimingAnimation = import('./src/reanimated2/animation/index').TimingAnimation;` is causing TypeScript to compile your sources with my local tsconfig.json configuration file inside my project. Which is causing issues described in here: #3087 

Inlude Fixes for #3087 

## Changes

To fix it I had to generate TypeScript declaration files based on your local `tsconfig.json` and include proper paths to types in `react-native-reanimated.d.ts` file.
I've added a script `type:generate:tsc:declaration` which create tsc declarations  for `src` folder and place it in new folder `lib/types`. 
Also made some interface exports to get rid of tsc errors during creation of declaration files.

## Test code and steps to reproduce

To reproduce to problem create a new RN application with typescript config, next install reanimated 2.5.0 and build it.

I've test this changes on my local RN project by copy-pasting react-native-reanimated folder to my node_modules folder.

My tsconfig.file as reference
`{
  "compilerOptions": {
    "baseUrl": ".",
    "composite": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "esModuleInterop": true,
    "importsNotUsedAsValues": "error",
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["esnext", "dom"],
    "module": "esnext",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": ["packages/*/lib"],
  "files": [
    "declarations.d.ts",
    "emotion.d.ts",
  ]
}`

### CODE REVIEW

**Comment by haveneersrobin** [comment]
Nice work @scyrych  !

**Review by Meph1k — APPROVED** [review]
Awesome!

**Comment by vinitsood** [comment]
Nice @scyrych !

**Comment by bang88** [comment]
Please publish a new release ASAP.  Thank you very much.

**Review by piaskowyk — APPROVED** [review]
Thanks! I really appreciate your commitment ❤️

**Pull request merged**
