### PR TITLE
Revert "Fix higher-order animations re-render behaviour"

### PR DESCRIPTION
**Pull request by tjzel**
Reverts software-mansion/react-native-reanimated#5647

### CODE REVIEW

**Review by szydlovsky — APPROVED** [review]

**Comment by efstathiosntonas** [comment]
@tjzel why this was reverted? thanks

**Comment by tjzel** [comment]
@efstathiosntonas btw where stack trace or more logs? https://github.com/software-mansion/react-native-reanimated/issues/5660 😅

**Comment by efstathiosntonas** [comment]
I wish I could replicate that!! I've being using 3.7.1 locally since yesterday and after 16hrs of work it never crashed 😢

**Comment by tjzel** [comment]
I don't know whether should I feel joy or sadness then 🤔

**Comment by efstathiosntonas** [comment]
sadness, I'm not the only one facing it haha

**Pull request merged**
