### PR TITLE
iOS: Support 0.64 and Hermes

### LINKED ISSUE #1372: Support Hermes on iOS
## EDIT

I've created a PR for this here: https://github.com/software-mansion/react-native-reanimated/pull/1469 🎉 

## Description

Since react-native 0.64 will ship with Hermes engine as an opt-in for iOS (see: https://github.com/react-native-community/releases/issues/207), I was wondering if the Hermes engine will be supported by react-native-reanimated v2?

### LINKED ISSUE #1485: [react-native 0.64-rc.1] [reanimated 2.0.0-rc.0] Use of undeclared identifier 'reanimatedModule'
## Description
build failed on iOS:

/node_modules/react-native-reanimated/ios/native/UIResponder+Reanimated.mm:46:79: Use of undeclared identifier 'reanimatedModule'

react native info:
```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 30.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/Documents/ReactNativeProj/fandeng/lingyue/node_modules/.bin/yarn
    npm: 7.0.8 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0-rc.1 => 0.64.0-rc.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
### Screenshots
image

## Package versions

- React: 17.0.1 => 17.0.1
- React Native: 0.64.0-rc.1 => 0.64.0-rc.1
- React Native Reanimated: 2.0.0-rc.0

### PR DESCRIPTION
**Pull request by mrousavy**
## Description

This adds support for react native 0.64 and Hermes on iOS.

I've tested this with `0.64.0-rc.1` which is available on npm.

## Changes

* Import `RCTEventDispatcher` since that's no longer imported in the module per default
* Update some preprocessor `#if`s to match the new `RNVERSION`
* If hermes is available, create a `HermesExecutorFactory` instead of the `JSCExecutorFactory`
* If hermes is available, create a hermes runtime instead of the JSC runtime
* Use `c++14` instead of `gnu++14` as `CLANG_CXX_LANGUAGE_STANDARD` since hermes also uses `c++14` (without this you'll see warnings on `pod install`)

## Related Issues

fixes #1485 
fixes #1372 

## Checklist

- [x] Ensured that CI passes
- [x] Ensured that it works on RN 0.64 (JSC)
- [x] Ensured that it works on RN 0.64 (Hermes)
- [x] Ensured that it works on RN 0.63 (JSC)
- [x] Ensured that it works on RN 0.62 (JSC)

> _"it works"_ = Xcode project successfully builds, app successfully starts and animations run as expected.

### CODE REVIEW

**Comment by mrousavy** [comment]
Also, I'm getting the following warnings after running `pod install` with hermes enabled on iOS:

```
[!] Can't merge user_target_xcconfig for pod targets: ["RNReanimated", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["RNReanimated", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["RNReanimated", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["RNReanimated", "hermes-engine"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.
```

I'll take a look at that to find out what that's about.

**Comment by mrousavy** [comment]
On Android I'm having build issues because it looks like the path to the `.aar` file is interpolated with the RNVERSION, which won't work since there is no `react-native-reanimated-64.aar`. I'll pass that to someone else, since I'm not that experienced in the Android ecosystem

Screenshot 2020-11-23 at 18 21 26

**Comment by jakub-gonet** [comment]
> Also, I'm getting the following warnings after running pod install with hermes enabled on iOS

[Hermes](https://github.com/facebook/hermes/blob/791bcd1025c9b31fdafb77b01ae142c2527a32e8/hermes-engine.podspec#L31) uses c++14 standard
[We](https://github.com/software-mansion/react-native-reanimated/blob/06045ec1e2d1940301412b7c40bf6899cb83f848/RNReanimated.podspec#L44) use gnu++14

You may try changing our Podspec to also use c++14, I don't know if we use any GNU extensions.

**Comment by finkef** [comment]
Can confirm that iOS builds using this branch directly as dependency with a brand new RN project and Hermes enabled. 

To get it running however, I had to apply [this](https://github.com/software-mansion/react-native-reanimated/pull/1471) fix.

**Comment by mrousavy** [comment]
In my case, I also had issues with the warnings about gnu++14 I mentioned - not sure why, as I've seen other libraries use gnu++14 without problems. Currently, using c++14 in the Podspec, I have no troubles building iOS. @jakub-gonet could you review when you have some time?

As for Android; this probably has to be done in a separate PR, since I'm not that experienced with the Android side.

**Comment by jakub-gonet** [comment]
I think @karol-bisztyga, @Szymon20000, @zrebcu411, or @piaskowyk are better reviewers for this one, this PR changes mostly code from Rea2.

**Comment by mrousavy** [comment]
So JFYI: On Android, I had to manually point the `build.gradle` file to the `react-native-reanimated-63.aar`, so we obviously need to build a `-64.aar` for RN 0.64. Then, I tried to get my app running, but it keeps crashing with the following exception:

```
2020-11-25 13:42:23.104 17248-17395/com.mrousavy.springsale E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.mrousavy.XXX, PID: 17248
    java.lang.IncompatibleClassChangeError: Found interface com.facebook.react.uimanager.events.EventDispatcher, but class was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/com.mrousavy.XXX-Xf0GGcPgwhI-36pFrrw8AQ==/base.apk)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:162)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1265)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by finkef** [comment]
I've noticed that after adding Reanimated (from this branch) and running `pod install`, Hermes is actually **not** being used anymore. It seems that it's not available anymore [here](https://github.com/facebook/react-native/blob/8663ec4f428efdd54bffe965460b1be26d780108/React/CxxBridge/RCTCxxBridge.mm#L41). I have no clue what might be causing this, but wanted to point it out.

@mrousavy Can you confirm that your app is actually still running on Hermes (by checking `typeof HermesInternal` for example)?

**Comment by mrousavy** [comment]
@finkef no, I cannot confirm that, because I noticed that too! it looks like this requires a bit more work than just changing some version checks. @Szymon20000, @karol-bisztyga, etc do you have any ideas?

**Comment by mrousavy** [comment]
I've tried initializing the JSI runtime (in NativeProxy.mm) with hermes, but `global.__jsiExecutorDescription` still returns JSC for me. (and `global.HermesInternal` is null). @finkef Can you confirm that uninstalling reanimated prints the correct values for `__jsiExecutorDescription` and `HermesInternal`?

**Comment by finkef** [comment]
@mrousavy Can confirm.

**Comment by mrousavy** [comment]
Fixed it. It was still creating the JSCExecutorFactory instead of the Hermes one.

<p align="center">

</p>

@finkef check out my latest commits, see if that works for you.

While this works and runs entirely on Hermes, I'm having trouble opening screens with animated code and gesture handlers that previously worked on RN 0.63:

<p align="center">
</p>

I'll look into that too.

**Comment by mrousavy** [comment]
Nevermind, I was doing something wrong. That error is a bit verbose, I was actually still applying an animated style to a non-animated view, would be nice if we could find a way to make those warnings/errors a bit cleaner.

This means, that now this PR is ready for review, as I am successfully running on `HermesInternal`/react native 0.64 with reanimated!! 🎉🎉

**Comment by finkef** [comment]
It's using Hermes now 👍 However, I'm greeted with the error below immediately when importing Reanimated. Trying to narrow down the issue, I believe that [this line](https://github.com/software-mansion/react-native-reanimated/blob/ec53d29fd329815a9aaddf8f01abb1b24be05f27/Common/cpp/Tools/RuntimeDecorator.cpp#L128) might not properly set the global value.

Simulator Screen Shot - iPhone 12 - 2020-11-25 at 22 03 45

**Comment by mrousavy** [comment]
@finkef Hm, weird. Random thought, could you try replacing `makeHermesRuntime` with `makeThreadSafeHermesRuntime` in [this line](https://github.com/software-mansion/react-native-reanimated/blob/c97d0759a47777ddccf5c6db830c0fbf70f3d85f/ios/native/NativeProxy.mm#L117) and see if that changes anything?

**Comment by finkef** [comment]
`jsi::ThreadSafeRuntime` doesn't inherit `jsi::Runtime`, so it won't let me use it or cast the pointers (at least with my *very* limited knowledge of C++ 😬 ).

**Comment by mrousavy** [comment]
[huh 🤨](https://github.com/facebook/hermes/blob/6e7eecd93bfd8c3f8c2f790a30b1fe98eefe5e28/API/jsi/jsi/threadsafe.h#L18) - either way, I'm not sure if we want/need the thread safe runtime. I'd like to hear what y'all think - I didn't run into any troubles using the normal runtime (as it is in this PR rn), so I'm not sure if it makes sense to use the thread safe one instead - or what the difference between those two even is, apart from being "thread safe".

**Comment by karol-bisztyga** [comment]
> `jsi::ThreadSafeRuntime` doesn't inherit `jsi::Runtime`, so it won't let me use it or cast the pointers (at least with my _very_ limited knowledge of C++ 😬 ).

https://github.com/facebook/hermes/blob/master/API/jsi/jsi/threadsafe.h#L18 looks like it does actually

**Comment by finkef** [comment]
[Here](https://github.com/finkef/reanimated-0.64.0-rc.1-repro) is the bare minimum setup with RN 0.64 RC1 and Reanimated using the fixes from this branch.

@mrousavy I'm curious if you get the same error running this project 🤔

**Comment by ltcaosj** [comment]
I got the same issue when trying Reanimated  2.0 rc0 with RN 0.64 RC1.

**Comment by mrousavy** [comment]
@finkef I'll (hopefully) check your repro out later if I find some time. At this point I'd just debug [this line](https://github.com/software-mansion/react-native-reanimated/blob/ec53d29fd329815a9aaddf8f01abb1b24be05f27/Common/cpp/Tools/RuntimeDecorator.cpp#L128) and see if it's using the correct hermes runtime (`rt` param). Maybe they changed the syntax and setting globals isn't just a `global().setProperty` anymore 🤷

**Comment by mrousavy** [comment]
hold on, @finkef could you try replacing [this line](https://github.com/software-mansion/react-native-reanimated/blob/ec53d29fd329815a9aaddf8f01abb1b24be05f27/src/reanimated2/core.js#L198)?

Instead of `_globalSetter`, this should probably be `global._globalSetter`

**Comment by finkef** [comment]
Oh god... Was missing the babel plugin in the repro that I threw together (too quickly apparently). 🤦‍♂️ Reanimated is running with Hermes now, had to apply #1471 with alpha.9.1 again, but that PR landed with rc.0.
@mrousavy Could you rebase this PR on rc.0?

**Comment by mrousavy** [comment]
haha no worries 👍 

Updated the branch - This means everything is working on RN 0.64 with Hermes enabled, and it still works for RN 0.63. I think Mike from callstack mentioned that the official RN 0.64 release is coming out on ~Monday, so it makes sense to prepare reanimated for it so it works on day one - @jakub-gonet can you assign someone to this PR/request a review?

**Comment by jakub-gonet** [comment]
Sure, done & done.

**Comment by finkef** [comment]
@mrousavy Great work! Can confirm that it's working out of the box now 🎉

**Comment by rpavlovs** [comment]
Installed from this PR and still getting the `_globalSetter` error mentioned above.

Latest master changes seem related: https://github.com/software-mansion/react-native-reanimated/pull/1482

@mrousavy could you rebase on `master` again please?

**Comment by rpavlovs** [comment]
Ah, my bad - I was just missing the babel plugin. It works! 🙂

**Comment by osdnk** [comment]
https://github.com/osdnk/react-native-reanimated/tree/64
I made it workable for android, but I'm too uncertain to discuss some things i did

**Comment by pontusab** [comment]
Can confirm this works on iOS RN 0.64 RC2

**Comment by jinshin1013** [comment]
Any update on the PR guys?

**Comment by a-eid** [comment]
this works for me as well, `0.64-rc2`

**Review by piaskowyk — CHANGES_REQUESTED** [review]
Ok, I tested this and it works on RN62, RN63, RN64-rc.2
Last time we talked about the problem in the Example app but I resolved this, but we stay with RN63 in the Example app at this moment, so that's why I ask you to revert changes in Example/ios/Podfile.lock If you change this then we can merge this 🎉
Good job! 👏

**Comment by mrousavy** [comment]
@piaskowyk Reverted the changes in the Podfile.lock ✅

**Review by piaskowyk — APPROVED** [review]

**Pull request merged**
