### PR TITLE
feat: add fallback for not yet supported RN versions

### PR DESCRIPTION
**Pull request by WoLewicki**
## Description

PR checking if `aar` for `react-native` version exists, and if no, looking for `aar` for lower versions.

## Test code and steps to reproduce

Add RN 0.67 in your project and try build with and without this change.

After removing the aars from folder, such error is thrown:
image

## Checklist

- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by mikehardy** [comment]
This is fabulous! I was going to try a test integration of 0.67.0-rc.0 as a service to RN release-testers but I was blocked on reanimated support. If you release another 2.3.0-beta on npmjs with this I'll test build it all together and report any issues I find / any solutions I try for any issues (though I must say last time I tried 2.3.0 at least in my app it all worked for me except a couple null pointers which already have merged fixes :-) )

**Comment by edisson89** [comment]
* What went wrong:
Included build '/home/edisson/React-Native/04-navegacionApp/node_modules/react-native-gradle-plugin' does not exist.

**Comment by edisson89** [comment]
hello help me|

**Comment by tomekzaw** [comment]
@edisson89 Sorry for the delay. Which version of react-native-reanimated are you using? Do you have react-native-gradle-plugin installed?

**Comment by mikehardy** [comment]
That package should be a transitive dependency of react-native - https://github.com/facebook/react-native/blob/72e1eda0736d34d027e4d4b1c3cace529ab5dcf3/package.json#L111

it *should* be there

**Comment by tomekzaw** [comment]
It looks like it was added quite recently: https://github.com/facebook/react-native/commit/805afe48470d0b96613d878ac221b57d47d0a70d

**Pull request merged**
