### PR TITLE
Inject `_WORKLET` to RN runtime

### LINKED ISSUE #4506: V3 Failed to create a worklet. Did you forget to add Reanimated Babel plugin in babel.config.js?
### Description

Error: Failed to create a worklet. Did you forget to add Reanimated Babel plugin in babel.config.js?

This error appeared randomly when i was rebuilding my application on an update branch (didn't do any particular change to packages when the error popped up,  and i already had rebuilt many times the app on this branch), in production everything works fine an correctly, but when i try to launch the app on the simulator this error pops up, both on android and ios, this is a preview of my babel.config.js: 

`
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ['module:react-native-dotenv', {
      'envName': 'APP_ENV',
      'moduleName': 'react-native-dotenv',
      'path': '.env'
    }],
    'react-native-reanimated/plugin'
  ]
};
`

is there something i'm missing? i didn't actually change anything and even clearing the whole env many times and restarting the pc didn't actually solve anything (i've also tried to go with npm start -- --reset-cache but nothing)

I've found other issues on the repo, also from reanimated v2 but every solution was leading to the babel.config.js, and to me mine looks correct.

### Steps to reproduce

1. npm start --reset-cache 

### Snack or a link to a repository

The repo is private

### Reanimated version

3.2.0

### React Native version

0.71.8

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

_No response_

### Acknowledgements

Yes

### LINKED ISSUE #4507: Missing 'react-native-reanimated/plugin'
### Description

Hi, I'm trying to install the new release, but there seems to be something missing in the plugin directory.

Obviously my babel configuration is correct, I just updated the library.

image

I took a look at the build, and indeed there seem to be some files missing.

Version 3.1.0:
image

Version 3.2.0:
image

### Steps to reproduce

1. Upgrade to react-native-reanimated@3.2.0
2. Try to run the app

### Snack or a link to a repository

none

### Reanimated version

3.2.0

### React Native version

0.71.8

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by tomekzaw**
## Summary

Fixes #4506 and fixes #4507.

### CODE REVIEW

**Review by t0ma5h — APPROVED** [review]

**Comment by leandro-carlos** [comment]
where i inject `_WORKLET` ?

**Comment by t0ma5h** [comment]
@tomekzaw is there an estimate to when this will get merged or should i just fork it 😁?

**Review by samyos — APPROVED** [review]

**Comment by tomekzaw** [comment]
Once we merge #4523 it will be only two places (one for each platform), and once we cleanup runtime initialization hopefully it will be just one 😄

**Review by piaskowyk — APPROVED** [review]

**Comment by piaskowyk** [comment]
According to my investigation, in out code is possible to call worklet function before globals initialisation - `runOnUI` doesn't imports `core.ts`
```
import { useSharedValue } from 'react-native-reanimated';
console.log(_WORKLET, useSharedValue); // doesn't work
console.log(useSharedValue, _WORKLET); // works
```

**Comment by alistairholt** [comment]
Great to see this merged. Will it make it into a release soon?

**Comment by tomekzaw** [comment]
Yep, we're releasing 3.3.0 today.

**Pull request merged**
