### PR TITLE
Ensure compatability with Jest 28

### PR DESCRIPTION
**Pull request by matt-oakes**
## Description

Fixes for Jest 28 compatability (Issue #3215)

## Changes

- Change the import for expect to maintain compatability with Jest 28.
- Updated the documentation to ensure the enviornment is set up before running the script.

## Checklist

- [x] Included code example that can be used to test this change
- [x] Updated TS types
- [x] Added TS types tests
- [x] Added unit / integration tests
- [x] Updated documentation
- [x] Ensured that CI passes

### CODE REVIEW

**Comment by piaskowyk** [comment]
Hey 👋 Thanks for the PR! 
Do these changes compatible with Jest versions older than 28?

**Comment by mayconline** [comment]
> Hey wave Thanks for the PR! Do these changes compatible with Jest versions older than 28?

I believe no, this solution is a braking change for v28, 
link helper upgrade: https://jestjs.io/pt-BR/docs/upgrading-to-jest28

**Comment by simoneb** [comment]
Any plans to release this?

**Comment by wmiklasewicz** [comment]
Hey guys, any update on that one?

**Comment by piaskowyk** [comment]
Thanks for your PR! I will add to it backward compatibility.

**Pull request merged**
