### PR TITLE
Feat: Allow for automatic exports of functions

### LINKED ISSUE #325: Automatically import Animated operators
see #503

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #325

### CODE REVIEW

**Comment by wcandillon** [comment]
@satya164 @osdnk @kmagiera I tried this version of reanimated on my reanimated course material. And it works great :)

**Comment by wcandillon** [comment]
@osdnk Thks :))

**Comment by jakub-gonet** [comment]
[CI build failed](https://travis-ci.org/software-mansion/react-native-reanimated/jobs/626326040) on master, I think we have to disable `import/no-named-as-default` eslint rule or change [imports](https://github.com/software-mansion/react-native-reanimated/pull/503/files#diff-90e18a8032bc64f5e4865642e05ef908R10-R12) to named imports as suggested by [@satya164](https://github.com/software-mansion/react-native-reanimated/issues/325#issuecomment-565129059)

**Comment by wcandillon** [comment]
Thks for notifying me. I've made a PR to fix the issue at
https://github.com/software-mansion/react-native-reanimated/pull/509

**Comment by jakub-gonet** [comment]
Cool, thanks for fast response

**Pull request merged**
