### PR TITLE
Add troubleshooting section to docs

### PR DESCRIPTION
**Pull request by jakub-gonet**
## Description

Added troubleshooting page to docs in order to create a list of common problems with Reanimated.

Suggested by @terrysahaidak in [this comment](https://github.com/software-mansion/react-native-reanimated/issues/1090#issuecomment-670948991)

### CODE REVIEW

**Comment by terrysahaidak** [comment]
Also lots of people actually forget to add babel plugin too.

**Comment by jakub-gonet** [comment]
Could you please provide some examples of this error? I'd like to create a mapping between error message - solution and I didn't use v2 that much 😄

**Comment by terrysahaidak** [comment]
I think it was this same error. Since babel plugin creates these closures. But there were more. I'll try and report back :)

**Review by jkadamczyk — APPROVED** [review]
Nice addition!

**Pull request merged**
