### PR TITLE
Fix deadlock in NodesManager.java (removes synchronous UI updates)

### LINKED ISSUE #2251: ANR caused in performOperations
## Description

We are seeing multiple ANRs with reanimated at the top of the stacktrace. These are not showing in bugsnag either, only on Play Store which is now penalising our app.

### Expected behavior

No ANR

### Actual behavior & steps to reproduce

```
"main" prio=5 tid=1 Waiting
```
```
  at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:868)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1023)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly (AbstractQueuedSynchronizer.java:1334)
  at java.util.concurrent.Semaphore.acquire (Semaphore.java:318)
  at com.swmansion.reanimated.NodesManager.performOperations (NodesManager.java:230)
  at com.swmansion.reanimated.NodesManager.onAnimationFrame (NodesManager.java:259)
  at com.swmansion.reanimated.NodesManager.access$000 (NodesManager.java:65)
  at com.swmansion.reanimated.NodesManager$1.doFrameGuarded (NodesManager.java:153)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1063)
  at android.view.Choreographer.doCallbacks (Choreographer.java:889)
  at android.view.Choreographer.doFrame (Choreographer.java:812)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1050)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7830)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1040)
```

## Snack or minimal code example

None available

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.2.0
- NodeJS: 16.0.0
- Xcode: 
- Java & Gradle: openjdk 11.0.8 gradle 6.5

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

### PR DESCRIPTION
**Pull request by SerhiyPetrosyuk**
## Description

Description and motivation for this PR.

Fixes #2251  .

## Changes

- Removes synchronous UI updates in NodesManager.java

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [x] Ensured that CI passes

### CODE REVIEW

**Comment by androideveloper** [comment]
Indeed, we need to get it merged at least for 2.x releases. See my comment under the issue
https://github.com/software-mansion/react-native-reanimated/issues/2251#issuecomment-1301916198

**Comment by jwoodmansey** [comment]
We are also seeing this a lot in production. Is there anything we can do to help this get moving?

**Comment by DomantasMk** [comment]
Also production suffering from this issue, in our case one of the issues was [bottom sheet clash with navigation](https://github.com/gorhom/react-native-bottom-sheet/issues/1041), can we get maintainers attention on this PR?

**Comment by androideveloper** [comment]
We patched this fix (using [rn-patch](https://www.npmjs.com/package/patch-package)) and shipped on prod. Number of ANRs decreased significantly! 🚀 In order to patch it properly, we needed to force rebuild reanimated from source by passing `reanimated = [ buildFromSource: true ]` to gradle config.

**Comment by DomantasMk** [comment]
We are trying to patch this fix, but it introduces some new problems, with our own animations and libraries. For example @gorhom/bottom-sheet is not behaving properly in some cases. So just leaving this if someone needs more info. Will leave more info if it solves the ANR for us.

**Comment by androideveloper** [comment]
One more thing, while patching we didn't change the method `enqueueUpdateViewOnNativeThread`, as it was causing build issues. For ANRs, we helped us a lot! For other issues, we are not aware of any on our side.

**Comment by DomantasMk** [comment]
Also confirming, that this dropped our ANR rate about 16% on Android.

**Comment by androideveloper** [comment]
Nice. The PR description is probably incorrect though?

> This PR addresses the problem from https://github.com/software-mansion/react-native-reanimated/issues/3879 on iOS

**Comment by androideveloper** [comment]
When are you planning to release it?

**Comment by tj-mc** [comment]
We are interested to know when this important patch will be released :D Thanks for your work

**Comment by tomekzaw** [comment]
@tj-mc This problem was fixed in #4239 which was released 3.1.0 and backported to 2.15.0.

**Comment by tj-mc** [comment]
Thanks for your response. Unfortunately we are on 3.6 (RN 73) and have experienced this crash 🤔 
But out of desperation we are applying this patch locally to remove semaphore

**Pull request closed without merging**
