### PR TITLE
fix: babel-plugin should not use property shorthands when transpiling worklets

### PR DESCRIPTION
**Pull request by asherLZR**
## Summary

The babel plugin transforms worklets' closure variables with property shorthand. This is somewhat problematic if the project uses common optimisations like the webpack DefinePlugin to transform these variable values later at build-time.

For example, we can end up transpiling with the DefinePlugin
```
_f._closure = {
  USE_STUB_IMPLEMENTATION,
  __DEV__
};
```
to 
```
_f._closure = {
  USE_STUB_IMPLEMENTATION,
  false
};
```

The solution here is to default to not using it. Fixes https://github.com/software-mansion/react-native-reanimated/issues/4130

## Test plan

See unit test. Tested in real project.

### CODE REVIEW

**Comment by tomekzaw** [comment]
Hey @asherLZR, thanks for submitting this PR. This is in fact a problem with `babel-plugin-transform-define` which has just been fixed in https://github.com/FormidableLabs/babel-plugin-transform-define/pull/86 and released in 2.1.3.

**Comment by asherLZR** [comment]
Hi @tomekzaw thanks for the review and the link. Forgive my limited understanding, but in our project we're using `webpack.DefinePlugin` which doesn't seem related to `babel-plugin-transform-define`.

However, I believe that it should be addressed by this PR https://github.com/webpack/webpack/pull/17231 where it isn't handling the shorthand property correctly. Closing this as a result.

**Comment by tjzel** [comment]
Hi @asherLZR. We have discussed this topic in the past with @tomekzaw I'm not sure whether it actually solves all problems related to this issue. Now (potentially) you could end up with `{ true: true }` instead of `{ true }` and both are equally bad. 

While I could approve this pull request since it looks fine and on the first glance it's irrelevant to our logic, piece of code you submitted creates a node that is an `objectProperty`. Therefore I have a strong belief it shouldn't be touched by any transform of this kind - if `{ __DEV__: __DEV__ }` is not transformed then `{ __DEV__ }` shouldn't be transformed as well. It seems like an issue - or on the complete contrary, conscious decision - in `webpack.DefinePlugin`. I will reopen this pull request but I think relevant research has to be done before merging it.

**Comment by tjzel** [comment]
@asherLZR 
I've fiddled a bit with Webpack and Webpack's DefinePlugin and were unable to get it to situation when using property shorthands leads to having illegal tokens in closure. Could you possibly provide some reproduction on this issue? 

I was using latest Webpack's version - could you see if the problem persists if you use it too?

**Comment by asherLZR** [comment]
@tjzel
Thanks for looking into it. In our project I can confirm that from webpack [v5.84.0](https://github.com/webpack/webpack/releases/tag/v5.84.0) onwards the issue is resolved with the mentioned fix to the DefinePlugin. Do you still require a reproduction?

**Comment by tjzel** [comment]
Oh, I must've missed that mentioned fix, sorry for that 😅. Therefore we are all good and we can close that!

**Pull request closed without merging**
