### PR TITLE
fix: BABEL_ENV should consider using production

### PR DESCRIPTION
**Pull request by jinliming2**
## Changes

BABEL_ENV should consider using production

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Review by tomekzaw — COMMENTED** [review]
Thanks for the PR.

Starting from 3.0.0-rc.3, Reanimated Babel plugin adds sourcemaps to worklets. In my case, this increases bundle size on web to 225 kB (compared to 27.6 kB without sourcemaps).

In #3650 I've proposed using `process.env.NODE_ENV === 'production'` to detect production build on web and it works for me (checked on Next.js + Reanimated example).

However, with this PR, the bundle still contains sourcemaps. In my case, `production.env.BABEL_ENV` is `undefined`.

Could you please describe which case is resolved by this PR?

**Comment by jinliming2** [comment]
@tomekzaw I'm using Re.Pack to build my RN app, which uses Webpack under the hood. In this case, `BABEL_ENV` was default set to 'production' when build in release mode.

**Comment by tomekzaw** [comment]
Great, thanks for information! So I think we can merge this.

**Review by tomekzaw — APPROVED** [review]

**Review by piaskowyk — APPROVED** [review]
🚀

**Pull request merged**
