### PR TITLE
fix ReferenceError: Property '_IS_FABRIC' doesn't exist

### PR DESCRIPTION
**Pull request by efstathiosntonas**
fixes https://github.com/software-mansion/react-native-reanimated/issues/5061

### CODE REVIEW

**Comment by piaskowyk** [comment]
Thank you a lot ❤️ I'm going to release it in patch 3.5.1

**Review by piaskowyk — APPROVED** [review]

**Comment by efstathiosntonas** [comment]
@piaskowyk thanks! Shouldn't the CIs fail in such scenario though? 🤔

**Comment by piaskowyk** [comment]
CI checks mainly building processes only, we haven't had runtime tests yet :/ But what is strange I tried to reproduce it on my computer and it seems to work - but it shouldn't 😅

**Comment by efstathiosntonas** [comment]
@piaskowyk it seems it worked automagically 🤣

**Comment by piaskowyk** [comment]
3.5.1 is ready - https://www.npmjs.com/package/react-native-reanimated/v/3.5.1

**Pull request merged**
