### PR TITLE
Added information about webpack configuration

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

Added information about webpack configuration.

image

### CODE REVIEW

**Comment by piaskowyk** [comment]
I wonder if giving the whole file is too much information, but in fact, the whole file is quite important. 🤔

**Review by jakub-gonet — APPROVED** [review]
Looks alright, I'd add some info about limitations and differences between web and native implementation.

**Comment by piaskowyk** [comment]
Unfortunately, I don't have enough time at this moment.

**Comment by piaskowyk** [comment]
Good point, but I will add this information next time. Unfortunately, I don't have enough time at this moment.

**Pull request merged**
