### PR TITLE
Release 2.10.0

### PR DESCRIPTION
**Pull request by piaskowyk**
## Descriptio
Temporary PR

### CODE REVIEW

**Comment by the-habu** [comment]
Any idea when this release can be done? I am really looking forward to it, as it contains wonderful fixes I need.
Anyway, thank you for the great work on this project.

**Comment by piaskowyk** [comment]
I'm doing everything that I can to release it this week

**Comment by d-moreira** [comment]
Any news on this @piaskowyk? Also waiting for this release.

**Comment by piaskowyk** [comment]
@d-moreira It should be tonight 💪

**Comment by the-habu** [comment]
I don't want to stress you out, just want to ask if you're not forgetting about releasing/tagging 2.10.0 the npm package? <3
Thank you for you effort!

**Pull request merged**
