### PR TITLE
fix TypeError: Cannot read property ' __value' of undefined

### PR DESCRIPTION
**Pull request by andrescalco**
Was facing some errors while testing with jest and found this quick fix.

### CODE REVIEW

**Comment by andrescalco** [comment]
Kudos to [adrianolsk](https://github.com/adrianolsk) on helping me with this

**Comment by GioCirque** [comment]
This should resolve #614 and #622

**Comment by jakub-gonet** [comment]
Isn't that treating symptoms instead of a cause? In what cases `getValue` should return `undefined`?

**Comment by Thomazella** [comment]
```
Isn't that treating symptoms instead of a cause? In what cases getValue should return undefined?
```
☝️ mocks should follow the types. That's the cause of the bug I think.

**Comment by balzdur** [comment]
I agree with @Thomazella.

I think the approach described here is better https://github.com/lucianomlima/react-navigation-v4-examples/pull/1

**Pull request merged**
