### PR TITLE
Docs video

### PR DESCRIPTION
**Pull request by piaskowyk**
Docs video

### CODE REVIEW

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317260-b3ccbe00-c2de-11eb-8434-8998b12dfa3c.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317304-c1824380-c2de-11eb-8aed-4c83cfe2f2cc.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317341-cc3cd880-c2de-11eb-9d72-4065c740667e.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317374-d52daa00-c2de-11eb-9fc5-320dfaf50440.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317406-deb71200-c2de-11eb-8dee-c658a4e1e47a.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317439-e971a700-c2de-11eb-89d7-1a934922b7fd.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317473-f42c3c00-c2de-11eb-8772-b366c2ddde7f.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317529-04441b80-c2df-11eb-9627-c56e986e44c1.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317554-0efeb080-c2df-11eb-88cf-6ec47778dccb.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317587-1a51dc00-c2df-11eb-937a-c53a237afca2.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120317603-22118080-c2df-11eb-9083-b5ba3f043dbc.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120326638-39ee0200-c2e9-11eb-8dca-3f3b999c5017.mov

**Comment by piaskowyk** [comment]
https://user-images.githubusercontent.com/36106620/120326673-44100080-c2e9-11eb-8b14-564d3b4e3102.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125057634-c094bc80-e0a9-11eb-98d9-0c8eed1e63b0.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058070-2e40e880-e0aa-11eb-98eb-326a34f23f39.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058126-40228b80-e0aa-11eb-8396-7f373af7fcbe.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058201-57617900-e0aa-11eb-951f-46ac27787d3e.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058243-60524a80-e0aa-11eb-94c8-79728688e2f3.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058307-6e07d000-e0aa-11eb-8379-4536c0806aee.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058359-79f39200-e0aa-11eb-8c78-c31e461e3748.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125058418-8841ae00-e0aa-11eb-9ac1-39df437512c4.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/125463255-04502655-3147-4d15-ae5b-f327666eadff.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/134476174-f7e2f5d6-4247-4f7e-8b84-7f41fca988b9.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/134477204-168feed8-1846-4d43-8158-cdb16db180e2.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/134477879-e697aa03-b94d-4a65-b076-5ec3800310e3.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/134478585-71c601ae-137f-44e4-a58f-4bb6b60f6bdf.mov

**Comment by jmysliv** [comment]
https://user-images.githubusercontent.com/48885911/134479266-5c7342f5-7453-4389-a6c5-5070e3673822.mov

**Pull request closed without merging**
