### PR TITLE
Fix types for `useAnimatedStyle()`

### PR DESCRIPTION
**Pull request by mrousavy**
* Only allows style objects to be used, no more arrays, `false`, `undefined`, whatever

## Description

Related to #1253 

## Changes

* Added type `AnimatedStyleProp` which is essentially a stripped down version of react-native's `StyleProp` which also has animated properties inside. This new style prop disallows arrays (and `false, `undefined`, `null`) as return values for `useAnimatedStyle`

### CODE REVIEW

**Comment by jakub-gonet** [comment]
@terrysahaidak, @wcandillon could you please check it? I'm not that familiar with RN types :/

@mrousavy, could you fix the conflict?

**Comment by wcandillon** [comment]
@mrousavy ping me once the conflict is fixed and I will review it.

**Comment by mrousavy** [comment]
@wcandillon 🏓

**Comment by wcandillon** [comment]
if this syntax is allowed at runtime, that looks good 👍🏽

**Comment by jakub-gonet** [comment]
Cool, @mrousavy could you also add some tests for this change to ts test file?

**Comment by jakub-gonet** [comment]
@mrousavy 🏓

**Comment by mrousavy** [comment]
@jakub-gonet @wcandillon  I've never written type-tests for TypeScript before, could you explain what you're expecting or at what file I'd have to look at?

**Comment by jakub-gonet** [comment]
Yeah, sure.

We have [a TS test file](https://github.com/software-mansion/react-native-reanimated/blob/master/react-native-reanimated-tests.tsx) in the repository which just uses typings from main TS file. Please add some code that compiles and uses different types for `useAnimatedStyle` so we can verify that `tsc --check` passes.

**Comment by mrousavy** [comment]
Thanks! I've added some tests, could you take a look and tell me if they're valid? `npm run type:check` ran successfully.

**Comment by jakub-gonet** [comment]
Yeah, we had tests for happy paths, I like `@ts-expect-error` usage to test arguments of the wrong type, great idea.

I can merge it after CI passes (we check TS types there).
Thanks for your contribution!

**Review by jakub-gonet — APPROVED** [review]

**Pull request merged**
