### PR TITLE
Bumped gesture-handler and screens dependencies

### PR DESCRIPTION
**Pull request by Kwasow**
## Description

`react-native-screens: software-mansion/react-native-screens#568e588817538740dff23a3590748614d4c346e3 => 3.15.0`

`react-native-gesture-handler: 2.4.2 => 2.5.0`

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Review by tomekzaw — APPROVED** [review]
TODO:
* Bump dependencies in Example app
* Add package.json in CI paths

**Review by piaskowyk — APPROVED** [review]
👍

**Review by tomekzaw — APPROVED** [review]

**Comment by piaskowyk** [comment]
What we can do with broken CI? 
`Android NDK: ERROR:/home/runner/work/react-native-reanimated/react-native-reanimated/FabricExample/node_modules/react-native-gesture-handler/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file`
https://github.com/software-mansion/react-native-reanimated/runs/7808165108?check_suite_focus=true

**Comment by piaskowyk** [comment]
I tested it locally, and it worked for me.

**Comment by Kwasow** [comment]
I think the CI might be fixed by #3456

**Pull request merged**
