### PR TITLE
fix: missing imports to DevMenuUtils for compatibility with version 72

### LINKED ISSUE #6076: Android build failure v3.12.0
### Description

Android build failing on 3.12.0:

```
> Task :react-native-reanimated:compileReleaseJavaWithJavac
/root/repo/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/ReactHost/72/com/swmansion/reanimated/DevMenuUtils.java:5: error: cannot find symbol
    private void addDevMenuOption(ReactApplicationContext context, DevOptionHandler handler) {
                                  ^
  symbol:   class ReactApplicationContext
  location: class DevMenuUtils
/root/repo/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/ReactHost/72/com/swmansion/reanimated/DevMenuUtils.java:5: error: cannot find symbol
    private void addDevMenuOption(ReactApplicationContext context, DevOptionHandler handler) {
                                                                   ^
  symbol:   class DevOptionHandler
  location: class DevMenuUtils
/root/repo/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java:85: error: addDevMenuOption(ReactApplicationContext,DevOptionHandler) has private access in DevMenuUtils
    DevMenuUtils.addDevMenuOption(mContext.get(), this::toggleSlowAnimations);
                ^
/root/repo/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/ReactHost/72/com/swmansion/reanimated/DevMenuUtils.java:7: error: cannot find symbol
    if (context.getApplicationContext() instanceof ReactApplication) {
                                                   ^
  symbol:   class ReactApplication
  location: class DevMenuUtils
/root/repo/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/ReactHost/72/com/swmansion/reanimated/DevMenuUtils.java:8: error: cannot find symbol
      final DevSupportManager devSupportManager =
            ^
  symbol:   class DevSupportManager
  location: class DevMenuUtils
/root/repo/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/ReactHost/72/com/swmansion/reanimated/DevMenuUtils.java:9: error: cannot find symbol
          ((ReactApplication) context.getApplicationContext())
            ^
  symbol:   class ReactApplication
  location: class DevMenuUtils
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors

> Task :react-native-reanimated:compileReleaseJavaWithJavac FAILED
```

### Steps to reproduce

Build android

### Snack or a link to a repository

n/a

### Reanimated version

3.12.0

### React Native version

0.72.14

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by gronxb**
## Summary

Related Pull Request https://github.com/software-mansion/react-native-reanimated/pull/5997

Fixed #6076

Android build does not work for versions below 0.72.

image

## Test plan

Run `./gradlew bundleRelease` on versions below 0.72.

### CODE REVIEW

**Review by WoLewicki — APPROVED** [review]
Seems like my mistake to not add those here. Thanks for fixing it 🚀

**Review by WoLewicki — COMMENTED** [review]
Changing to `Comment` since we have a merge freeze cc @szydlovsky

**Review by WoLewicki — CHANGES_REQUESTED** [review]
Had to change to `Request changes` 😅

**Comment by szydlovsky** [comment]
The PR has been moved to https://github.com/software-mansion/react-native-reanimated/pull/6097 because of monorepo migration 😄

**Pull request closed without merging**
