### PR TITLE
Use animated reaction

### PR DESCRIPTION
**Pull request by karol-bisztyga**
## Description

Added a new hook - `useAnimatedReaction` which takes 2 arguments(both are worklets):
1. `prepare` - prepares data for the second argument. Value returned from this function is the only one argument passed to the following one
2. `react` - takes one argument which is a result from the previous function's invocation and just performs some specified operations

## Motivation

This hook has been added to allow performing some actions on some shared values' change. The key idea is all of the shared values included in the first worklet are the `inputs` set. Every time any of those change both worklets are triggered in the order specified above. Also the second worklet may modify any shared values excluding those used in the first worklet.

## Usage

```
useAnimatedReaction(
    () => {
        'worklet';
        return (x.value + y.value) / 2; // `data` below
    },
    (data) => {
        'worklet';
        if (sv.value < 100) {
            sv.value = data;
        }
    }
);
```

## Changes

`Hooks.js` - added `useAnimatedReaction` hook
`AnimatedReactionTest.js` - added simple test showing an example of using the new hook
`plugin.js` - added automatic workletization for the new hook

### CODE REVIEW

**Comment by kmagiera** [comment]
The description does not seem to be accurate. The problem we're solving is not the inability to update SV in UAS but rather the lack of an API to support some of the usecases we discussed on the group. Would rather see those examples listed here with answers of how this new API fills this gap.

Beside that I think we should automatically workletize methods provided to the new hook, the same way we do for other hooks (to avoid the necessity of writing `'worklet'` directive).

On top of that I think I understand reaction API a bit different. From what I understand the first method is not to prepare a data but mostly to tell whether the second method should or should not run. The first one is run on every input change and we want to avoid the reaction firing in certain scenarios.

**Comment by likern** [comment]
> The description does not seem to be accurate. The problem we're solving is not the inability to update SV in UAS but rather the lack of an API to support some of the usecases we discussed on the group. Would rather see those examples listed here with answers of how this new API fills this gap.
> 
> Beside that I think we should automatically workletize methods provided to the new hook, the same way we do for other hooks (to avoid the necessity of writing `'worklet'` directive).
> 
> On top of that I think I understand reaction API a bit different. From what I understand the first method is not to prepare a data but mostly to tell whether the second method should or should not run. The first one is run on every input change and we want to avoid the reaction firing in certain scenarios.

@karol-bisztyga This starts looking like an old V1 API with all conditions, `proc` etc. nodes.

```ts
const sharedWidth = useSharedValue(10)
const val = useSharedValue(10)
const style = useAnimatedStyle(() => {
  val.value = sharedWidth.value * 2
  return {
    width: sharedWidth.value + 1
  }
})
```

As I understand shared values and worklets have automatic reactivity, opposed to React Hooks.
When it comes to this exact use case this is very similar to React Hooks, where there is the same problem.
```ts
const [value, setValue] = useState(0);
  useEffect(() => {
    console.log(`[useEffect] whenever value is changed`);
    setValue(val => val + 1); // here should be render loop !
  }, [value])
```
this is solved by using reference with direct manipulation
```ts
const ref = useRef(0);
  useEffect(() => {
    console.log(`[useEffect] whenever value is changed`);
    ref.current = ref.current + 1; // no render loop
  }, [ref])
```

why we couldn't solve this using a similar concept, like `useSharedReference` (which disables reactivity and is just usual value)?

In general I think to be as close to React concepts as possible might eliminate a lot of problems,
because React Hooks already implemented there own patterns and solutions to solve newly aroused problems.

**Comment by likern** [comment]
We can rewrite example as this
```ts

const sharedWidth = useSharedValue(10)
const counterRef = useSharedReference(0);

// No need to do this computation in useAnimatedStyle
// with forever loop if we can do that in useDerivedValue

// on first render val has default value 50
// on all other renders will have current sharedWidth.value * 2
const val = useDerivedValue(() => {
  // do not cause rerender
  // changes are synchronous and visible immidiately
  counterRef.value = counterRef.value + 1;
  // on first render
 if (counterRef.value === 1) {
    return 50 // return default value
 } else {
    return sharedWidth.value * 2;
 }
})

const style = useAnimatedStyle(() => {
  // Use val.value for something usefull here
  return {
    height: val.value,
    width: sharedWidth.value + 1
  }
})
```

**Comment by karol-bisztyga** [comment]
> The description does not seem to be accurate. The problem we're solving is not the inability to update SV in UAS but rather the lack of an API to support some of the usecases we discussed on the group. Would rather see those examples listed here with answers of how this new API fills this gap.
> 
> Beside that I think we should automatically workletize methods provided to the new hook, the same way we do for other hooks (to avoid the necessity of writing `'worklet'` directive).
> 
> On top of that I think I understand reaction API a bit different. From what I understand the first method is not to prepare a data but mostly to tell whether the second method should or should not run. The first one is run on every input change and we want to avoid the reaction firing in certain scenarios.

Yes I accidentaly provided misleading description update, sorry about that the main goal is in fact to react to certain changes. 

Those methods for sure will be automatically workletized.

The first method does both of those things. What it's going to be used for mostly depends on the usecase.

**Comment by likern** [comment]
@software-mansion Why my comments were deleted?

**Comment by karol-bisztyga** [comment]
> @software-mansion Why my comments were deleted?

I'm sorry I made a mistake providing a description and they were not accurate anymore, I just wanted to clean up. Should have posted it as a draft in the fisrt place. Thank you for contribution anyway.

**Comment by yolpsoftware** [comment]
Why was this closed without a merge? `useAnimatedReaction` would be great instead of `useDerivedValue` without using the derived value :-)

**Comment by terrysahaidak** [comment]
could you describe your usecase @yolpsoftware ?

**Comment by yolpsoftware** [comment]
My use case is coupling several ScrollViews together (#949). So I need a worklet that runs whenever one of the scroll offsets changes (scroll offsets will be shared values, I guess).

I could use `useDerivedValue` for the worklet as in the [scrollTo docs](https://docs.swmansion.com/react-native-reanimated/docs/next/api/nativeMethods/scrollTo/), but as @karol-bisztyga pointed out in #1082, it does not seem clean to use `useDerivedValue` when we are not interested in the derived value. That was when you proposed to use `useAnimatedReaction` for this use case.

It does not seem to be clean naming when `useDerivedValue` is the only option to run worklets when a value changes. We should have a method named `useAnimatedReaction` or `runOnChange`, even if it is just a wrapper around something similar to `useDerivedValue`.

**Comment by karol-bisztyga** [comment]
Reopening due to incoming requests

**Review by Szymon20000 — APPROVED** [review]

**Pull request merged**
