### PR TITLE
fixed children disappearing on transition.change

### PR DESCRIPTION
**Pull request by CameronStuartSmith**
Fix relating to #272. Stops children from disappearing on transition.

### CODE REVIEW

**Comment by CameronStuartSmith** [comment]
Changes in TransitionUtils.java fixes both #272 & #257
Changes in ChangeTransition.java fixed only #272 but are no longer needed ( The transition util changed removed the need for ChangeTransition.java )

**Comment by adkenyon** [comment]
This fixes #272 for our app.

**Comment by neopit** [comment]
This fixes our issue on our app as well.
That fixed issue we encountered with Transition change and issue on zIndex.

I will be happy to see this fix approve. 
Thx for the fix.

**Comment by osdnk** [comment]
Thanks! It helps!

**Comment by osdnk** [comment]
closes #272, #257

**Comment by tijunoi** [comment]
I was just installed the library from the PR head to try if it solved my issues and it did. I've seen it was just merged to master. May I ask how long will it take to be released in npm?

**Pull request merged**
