### PR TITLE
Add web/js only support

### PR DESCRIPTION
**Pull request by terrysahaidak**

### CODE REVIEW

**Comment by gut4** [comment]
What is status of this? Any ETA?

**Comment by terrysahaidak** [comment]
I'm currently working on this in my free te so no ETA. I would appreciate any testing and bug reports here.

I can guide how to debug and turn it on.

**Comment by gut4** [comment]
Guide would be nice

**Comment by terrysahaidak** [comment]
> Guide would be nice

In the file called NativeReanimated.js there is native flag. It checks for availability of JSI provided native Reanimated module. You can just replace it with "false" and now you're running js version of Reanimated2.

The whole logic is executed on the same thread as everything else does.

The only big missing thing in the current implementation is topological sorting of mappers (you can refer to c++ implementation of the same algorithm).

**Comment by kesha-antonov** [comment]
Will it work with react-native-web?

**Comment by terrysahaidak** [comment]
Yeah, it should.

**Comment by terrysahaidak** [comment]
Closing it because the work on it is currently on different branch.

**Pull request closed without merging**
