### PR TITLE
Release 3.12.0

### PR DESCRIPTION
**Pull request by szydlovsky**
:shipit: 🚀

### CODE REVIEW

**Review by tjzel — APPROVED** [review]
Nice!

**Review by maciekstosio — APPROVED** [review]

**Comment by efstathiosntonas** [comment]
63050ae9df594c789a0710ab02559837

**Comment by irekrog** [comment]
@efstathiosntonas today is a holiday in Poland 😅

**Comment by gronxb** [comment]
When will it be released?

**Pull request merged**
