### PR TITLE
Dismiss layout animation if catalyst instance was destroyed

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

I added a check to dismiss the layout animation if the catalyst instance was destroyed. It sometimes throws null pointer exceptions during a fast refresh.

Fixes https://github.com/software-mansion/react-native-reanimated/issues/2481

Inspired by https://github.com/software-mansion/react-native-reanimated/pull/2559

### CODE REVIEW

**Review by tomekzaw — APPROVED** [review]

**Comment by fnando** [comment]
hey! Can we get another beta 2.3.0 beta release with this fix in? We just upgraded our app to react-native@0.66.3 and without this we can release the Android app. Thanks!

**Comment by MANTENN** [comment]
Is this pushed into the release branch because I'm getting this error https://github.com/software-mansion/react-native-reanimated/issues/2560
too
```
 Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at com.swmansion.reanimated.layoutReanimation.g.r(Unknown Source:219)
	at com.facebook.react.uimanager.z0$m.a(Unknown Source:14)
	at com.facebook.react.uimanager.z0$a.run(Unknown Source:135)
	at com.facebook.react.uimanager.z0.U(Unknown Source:53)
	at com.facebook.react.uimanager.z0.s(Unknown Source:0)
	at com.facebook.react.uimanager.z0$j.c(Unknown Source:31)
	at com.facebook.react.uimanager.f.a(Unknown Source:0)
	at com.facebook.react.modules.core.g$d.a(Unknown Source:46)
	at com.facebook.react.modules.core.a$a$a.doFrame(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	```

**Comment by MANTENN** [comment]
Odd enough Android builds with version 2.4.4 instead of 2.3.0-beta-2 which I was on. But now IOS crashes with 2.4.4 where 2.3.0-beta-2 worked with ISO.

**Comment by piaskowyk** [comment]
@MANTENN Do you use proguard? Look at this - https://docs.swmansion.com/react-native-reanimated/docs/next/fundamentals/installation#proguard

**Pull request merged**
