### PR TITLE
Add createWorklet and useWorkletCallback types

### PR DESCRIPTION
**Pull request by terrysahaidak**
## Description

This PR adds TS typings for the introduced in #1310 API

## Changes

- Added TypeScript definitions for useWorkletCallback and createCallback
- Added TS tests for useWorkletCallback and createCallback

### CODE REVIEW

**Comment by jakub-gonet** [comment]
CI fail
https://travis-ci.org/github/software-mansion/react-native-reanimated/jobs/733207829#L225

**Comment by terrysahaidak** [comment]
Yeah, because #1310 hasn't been merged yet.

**Comment by jakub-gonet** [comment]
Ah, I see. Could you do this PR against #1310 branch then?

**Comment by terrysahaidak** [comment]
I will be able to do rebase in 30m if it's required.

**Pull request merged**
