### PR TITLE
Add basic JS implementation support for react-native-windows 🎉

### PR DESCRIPTION
**Pull request by piaskowyk**
## Summary

This pull request introduces support for react-native-windows! 🎉 However, please note that it does not include native support. Instead, it enables the web implementation of Reanimated for the Windows platform.

Kudos to [@hsjoberg](https://github.com/hsjoberg) because his PR [#4669](https://github.com/software-mansion/react-native-reanimated/pull/4669) was an inspiration for this one! 🙌

## Test plan

```
npx react-native init reanimatedWindows --version "latest"
cd reanimatedWindows
npx react-native-windows-init --overwrite
yarn add react-native-reanimated
npx react-native run-windows
```

### CODE REVIEW

**Review by tomekzaw — APPROVED** [review]

**Review by tjzel — APPROVED** [review]
I approve but I'm scared

**Comment by hsjoberg** [comment]
I cannot check this myself, but does calling `console.{warn|error}` work fine on react-native-windows?

On #4669, I had to make sure `initializeUIRuntime()` does not run, as it is manipulating the console object and running stuff in worklets, which obviously won't work for the basic react-native-windows support
Otherwise calling `console.{warn|error}` would throw an undefined exception and enter an infinite error loop.


https://github.com/software-mansion/react-native-reanimated/pull/4669/files#diff-78a1300914cdf4318497f5e74a0a44c4f5174ef2567339edeb0d646c1ddbfaf0R158-R160
```diff
--if (!isWeb()) {
++if (!isWeb() && !isMacos()) {
  initializeUIRuntime();
}

```

---

> I approve but I'm scared

With my limited understanding, I think it should be fine as long as people use `isWeb()` when dealing web/DOM stuff (like #4805) and not `shouldBeUseWeb()`.

**Comment by exotexot** [comment]
@piaskowyk I have a weird issue where react-native-reanimated is running in DEBUG mode, but in RELEASE mode it crashes. Actually it crashes with the same message reported here.: https://github.com/software-mansion/react-native-reanimated/issues/4663

```
Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
- not rebuilding the app after installing or upgrading Reanimated
**- trying to run Reanimated on an unsupported platform** (?)
- running in a brownfield app without manually initializing the native library, js engine: hermes
```


Just for the record, I just need a running react-native-reanimated for my project to satisfy dependencies for react-navigation.



```
  "dependencies": {
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "react": "^18.2.0",
    "react-native": "^0.72.4",
    "react-native-reanimated": "^3.4.2",
    "react-native-windows": "^0.72.7",
  },
```


```
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22000
  CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Memory: 4.58 GB / 15.97 GB
Binaries:
  Node:
    version: 18.15.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.5.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33516.290 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.4
    wanted: ^0.72.4
  react-native-windows:
    installed: 0.72.7
    wanted: ^0.72.7
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

**Comment by piaskowyk** [comment]
I will try to reproduce it 🫡 But as a workaround you can just remove throwing of this exception and it should be enough for you use-case.

**Comment by WilliamWelsh** [comment]
> @piaskowyk I have a weird issue where react-native-reanimated is running in DEBUG mode, but in RELEASE mode it crashes. Actually it crashes with the same message reported here.: #4663
> 
> ```
> Error: [Reanimated] The native part of Reanimated doesn't seem to be initialized. This could be caused by
> - not rebuilding the app after installing or upgrading Reanimated
> **- trying to run Reanimated on an unsupported platform** (?)
> - running in a brownfield app without manually initializing the native library, js engine: hermes
> ```
> 
> Just for the record, I just need a running react-native-reanimated for my project to satisfy dependencies for react-navigation.
> 
> ```
>   "dependencies": {
>     "@react-navigation/drawer": "^6.6.3",
>     "@react-navigation/native": "^6.1.7",
>     "@react-navigation/stack": "^6.3.17",
>     "react": "^18.2.0",
>     "react-native": "^0.72.4",
>     "react-native-reanimated": "^3.4.2",
>     "react-native-windows": "^0.72.7",
>   },
> ```
> 
> ```
> info Fetching system and libraries information...
> System:
>   OS: Windows 10 10.0.22000
>   CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
>   Memory: 4.58 GB / 15.97 GB
> Binaries:
>   Node:
>     version: 18.15.0
>     path: C:\Program Files\nodejs\node.EXE
>   Yarn:
>     version: 1.22.19
>     path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
>   npm:
>     version: 9.5.0
>     path: C:\Program Files\nodejs\npm.CMD
>   Watchman: Not Found
> SDKs:
>   Android SDK: Not Found
>   Windows SDK:
>     AllowDevelopmentWithoutDevLicense: Enabled
>     AllowAllTrustedApps: Enabled
>     Versions:
>       - 10.0.18362.0
>       - 10.0.19041.0
>       - 10.0.22000.0
>       - 10.0.22621.0
> IDEs:
>   Android Studio: Not Found
>   Visual Studio:
>     - 17.5.33516.290 (Visual Studio Community 2022)
> Languages:
>   Java: Not Found
>   Ruby: Not Found
> npmPackages:
>   "@react-native-community/cli": Not Found
>   react:
>     installed: 18.2.0
>     wanted: ^18.2.0
>   react-native:
>     installed: 0.72.4
>     wanted: ^0.72.4
>   react-native-windows:
>     installed: 0.72.7
>     wanted: ^0.72.7
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: true
>   newArchEnabled: false
> iOS:
>   hermesEnabled: Not found
>   newArchEnabled: Not found
> ```

Did you ever solve this?

**Comment by HunainHumail** [comment]
We developers need support of react native reanimated on react native windows.. React Native Reanimated is a very big library, used in almost every project! I just separated my react native windows code base from my main project just because it was crashing on reanimated and my android and ios apps were using that for some classy animations. So there must be support for React Native Windows. Waiting for that
@piaskowyk

**Pull request merged**
