### PR TITLE
make build work on m1/m2 without rosetta

### PR DESCRIPTION
**Pull request by philipheinser**

### CODE REVIEW

**Comment by piaskowyk** [comment]
I am not sure if it is a problem with the `CMake` version. It's more looks like a problem with the NDK version. With NDK version do you use?

**Comment by philipheinser** [comment]
@piaskowyk 
> I am not sure if it is a problem with the `CMake` version. It's more looks like a problem with the NDK version. With NDK version do you use?

ndkVersion = "25.2.9519653"

**Comment by tjzel** [comment]
Hi @philipheinser 

Could you elaborate more about what exactly are you fixing?

**Comment by philipheinser** [comment]
@tjzel Without it wouldn’t build on m2 arm chip without Rosetta before

**Comment by tjzel** [comment]
Since we rely on `x86` binaries when we develop `react-native-reanimated` and this is the only request to make it buildable without Rosetta we're closing this PR for now.

**Pull request closed without merging**
