### PR TITLE
Release 2.3.0-beta.4 🎉

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

Release 2.3.0-beta.4 🎉

### CODE REVIEW

**Review by kkafar — APPROVED** [review]
👍🏼

**Comment by tomekzaw** [comment]
😢 

https://user-images.githubusercontent.com/20516055/143539824-f843f191-40ad-4426-b5e5-eb854d324ad5.mov

**Comment by nandorojo** [comment]
FYI: Getting this error when running on Web with Next.js. Works fine if I downgrade to 2.2.

```sh
error - ../../node_modules/react-native-reanimated/lib/createAnimatedComponent.js
Error: Cannot find module '@babel/preset-typescript'
Require stack:
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/react-native-reanimated/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/react-native-reanimated/node_modules/@babel/core/lib/config/files/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/react-native-reanimated/node_modules/@babel/core/lib/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/react-native-reanimated/plugin.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/files/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/webpack/loaders/createBabelLoader.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/webpack/loaders/createAllLoaders.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/webpack/loaders/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/webpack/addons/withUnimodules.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/webpack/addons/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/node_modules/@expo/webpack-config/addons/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/apps/next/node_modules/@expo/next-adapter/build/withExpo.js
- /Users/fernandorojo/Developer/madison-hacks/marble/apps/next/node_modules/@expo/next-adapter/build/index.js
- /Users/fernandorojo/Developer/madison-hacks/marble/apps/next/next.config.js
    at loadPreset.next (<anonymous>)
    at createDescriptor.next (<anonymous>)
(node:89284) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
```

I tried to fix it by deleting `.next` and running `yarn add @babel/preset-typescript`, but no luck.

**Comment by piaskowyk** [comment]
@nandorojo Could you open a new issue with a description of how to reproduce it?

**Comment by nandorojo** [comment]
@piaskowyk I ended up fixing it and put an update at the bottom of the comment (it might look a bit hidden.)

**Pull request merged**
