### PR TITLE
fix: use proper classes for bridgeless

### PR DESCRIPTION
**Pull request by WoLewicki**
## Summary

Thanks to @lukmccall we discovered that on bridgeless mode invoking `getReactInstanceManager` creates another instance of application. This PR makes it behave correctly there. 

## Test plan

Run application and see that without this code, on bridgeless, there is no additional button in dev menu since it is created and the button is added in another instance.

### CODE REVIEW

**Review by tomekzaw — COMMENTED** [review]
Can we do something to avoid duplicating whole `NativeProxyCommon.java`?

**Comment by WoLewicki** [comment]
I can move this method only to a new file and make sourceSets from it. Do you want it?

**Comment by tomekzaw** [comment]
Yes, please

**Comment by WoLewicki** [comment]
Done

**Review by tomekzaw — APPROVED** [review]
better

**Pull request merged**
