### PR TITLE
@karol/uas multiple views

### PR DESCRIPTION
**Pull request by karol-bisztyga**
This was created as a response to this feature request
https://github.com/software-mansion/react-native-reanimated/issues/920 

It introduces the possibility of using one outcome of `useAnimatedStyle` for a multiple views.

### CODE REVIEW

**Comment by Szymon20000** [comment]
I think that this approach won't work property. That's because updating a viewTags array will not change frozenArray on UI side. It won't update on rerender.

**Comment by karol-bisztyga** [comment]
> I think that this approach won't work property. That's because updating a viewTags array will not change frozenArray on UI side. It won't update on rerender. However, I think it can be done with mutable string.

The render itself is not really a problem - it works ok. But excluding views from the component and including them again results in not updating styles with current values(this is because new view tag ids are assigned but outdated are used for updating).

**Comment by Szymon20000** [comment]
> > I think that this approach won't work property. That's because updating a viewTags array will not change frozenArray on UI side. It won't update on rerender. However, I think it can be done with a mutable string.
> 
> The rerender itself is not really a problem - it works ok. But excluding views from the component and including them again results in not updating styles with current values(this is because new view tag ids are assigned but outdated are used for updating).

That's what I meant. We won't be able to update FrozenArray on the second render and next ones.

**Comment by kmagiera** [comment]
As per our discussion on slack I understand that we should close this one. Feel free to reopen if that wasnt the case

**Pull request closed without merging**
