### PR TITLE
Pass ref into FlatList with forwardRef

### LINKED ISSUE #2976: ForwardRef and Animated.FlatList not set
## Description

Should Animated.FlatList be using forwardRef like this?

```
const ReanimatedFlatlist = forwardRef<FlatList, ReanimatedFlatlistProps<any>>(
  ({ itemLayoutAnimation, ...restProps }, ref) => {
    const cellRenderer = React.useMemo(() => createCellRenderer(itemLayoutAnimation), []);
    return <AnimatedFlatList ref={ref} {...restProps} CellRendererComponent={cellRenderer} />;
  },
);
````

I noticed i couldn't use `useRef` with Animated.FlatList as you get the warning about `Function components cannot be given refs`

I'm happy to raise a PR, do let me know

### Expected behavior

can use `useRef` with Animated.FlatList, particular to scroll with react navigation `useScrollToTop` hook

### Actual behavior & steps to reproduce

Couldn't use `useRef` with Animated.FlatList as you get the warning about `Function components cannot be given refs`

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native-reanimated              |     2.3    |
| expo                                 |    44    |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

ps Thank you for an amazing library

### PR DESCRIPTION
**Pull request by naftalibeder**
## Description

Fixes #2976.

## Changes

Wraps `FlatList` in `forwardRef`.

## Checklist

- [ ] ~Included code example that can be used to test this change~
- [ ] ~Updated TS types~
- [ ] ~Added TS types tests~
- [ ] ~Added unit / integration tests~
- [ ] ~Updated documentation~
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by naftalibeder** [comment]
Not sure what to make of the test failure [here](https://github.com/software-mansion/react-native-reanimated/runs/6313605788?check_suite_focus=true#step:6:10). The type `ForwardedRef` does appear to be [exported in the React namespace](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L543). Any ideas?

**Review by b0iq — COMMENTED** [review]
Good job 👍

**Comment by wassgha** [comment]
Could we merge this please? @b0iq

**Review by b0iq — APPROVED** [review]

**Review by piaskowyk — APPROVED** [review]
Thanks for the fix! and sorry for my delay 😕

**Pull request merged**
