### PR TITLE
Reanimated 120 fps

### PR DESCRIPTION
**Pull request by tomekzaw**
## Description

This PR adds support for 120 fps on iOS devices. On Android, 120 fps is already supported without any changes.

### Android

There's nothing to do. Just make sure that your device has 120 fps mode enabled in the general system settings.

### iOS

Add the following lines to `Info.plist` of your app:

```diff
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	...
+	<key>CADisableMinimumFrameDurationOnPhone</key>
+	<true/>
</dict>
</plist>
```

Once added, it should be visible Project Settings > Info > Custom iOS Target Properties:

If it's not, then restart Xcode. Finally, build and run your app as usual.

## Example

<details>
<summary>FpsCounter.tsx</summary>

```tsx
import Animated, {
  runOnUI,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from 'react-native-reanimated';

import React from 'react';
import { View } from 'react-native';

export default function FpsCounter() {
  const [state, setState] = React.useState(false);

  const x = useSharedValue(0);

  React.useEffect(() => {
    runOnUI(() => {
      'worklet';
      global.frameTimestamps = [];
    })();
    x.value = withSpring(state ? 360 : 0);
  }, [state]);

  const handlePress = () => {
    setState((state) => !state);
  };

  const styles = useAnimatedStyle(() => {
    if (_WORKLET) {
      const now = _frameTimestamp;
      global.frameTimestamps.push(now);
      if (global.frameTimestamps.length >= 20) {
        const first = global.frameTimestamps.shift();
        const fps = (1000 / (now - first)) * global.frameTimestamps.length;
        console.log(`${fps.toFixed(3)} fps`);
      }
    }

    return {
      transform: [{ rotate: `${x.value}deg` }],
    };
  });

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Animated.View
        style={[{ width: 200, height: 200, backgroundColor: 'red' }, styles]}
        onTouchStart={handlePress}
      />
    </View>
  );
}
```

</details>

## Changes

- Set preferred frames per second for display link to 120

## Test code and steps to reproduce

1. Copy `FpsCounter.tsx` to your app
2. Modify `Info.plist` of your app (iOS only)
3. Build and run your app
5. Click on the red square to start animation
6. Check FPS count in the console output

console

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

## References

* https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=objc
* https://developer.apple.com/documentation/quartzcore/cadisplaylink
* https://developer.apple.com/documentation/quartzcore/cadisplaylink/1648421-preferredframespersecond?language=objc

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]
so smooooooth 🚀

**Comment by Bijiabo** [comment]
Also need set CADisplayLink preferredFrameRateRange property, reference is here: https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro

**Comment by wmonecke** [comment]
I am using Reanimated V3 with RN 0.72.2 but the UI is still capped at 60fps.

Any ideas?

**Comment by tomekzaw** [comment]
@wmonecke What device do you use? Does it have energy save mode enabled? If it's an iPhone 13 Pro, did you remember to disable `CADisableMinimumFrameDurationOnPhone` in `Info.plist`? It's really difficult to answer your question without these details.

**Comment by wmonecke** [comment]
@tomekzaw You are right! I am a fool and didn't read the `CADisableMinimumFrameDurationOnPhone` stuff. Thank you!

**Comment by tomekzaw** [comment]
@wmonecke Worry not, it happens to everyone! Thanks for responding!

**Comment by MariuzM** [comment]
Sorry i think i'm missing something, i'm testing the FPS counter but getting some errors 

image

**Comment by tomekzaw** [comment]
@MariuzM Looks like the example is outdated and there should be `global.__frameTimestamp` instead of `_frameTimestamp`.

**Comment by MariuzM** [comment]
Thank you worked, getting 120fps

**Comment by MariuzM** [comment]
If any one else wants to use FpsCounter without TS errors

```ts
import React, { useEffect, useState } from 'react';
import { View } from 'react-native';
import Animated, {
  runOnUI,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
} from 'react-native-reanimated';

declare const global: {
  frameTimestamps: number[];
  __frameTimestamp: number;
};

declare const _WORKLET: boolean;

export default function FpsCounter() {
  const [state, setState] = useState(false);
  const x = useSharedValue(0);

  useEffect(() => {
    runOnUI(() => {
      'worklet';
      global.frameTimestamps = [];
    })();
    x.value = withSpring(state ? 360 : 0);
  }, [state, x]);

  const handlePress = () => {
    setState((state) => !state);
  };

  const styles = useAnimatedStyle(() => {
    if (_WORKLET) {
      const now = global.__frameTimestamp;
      global.frameTimestamps.push(now);
      if (global.frameTimestamps.length >= 20) {
        const first = global.frameTimestamps.shift() || 0;
        const fps = (1000 / (now - first)) * global.frameTimestamps.length;
        console.log(`${fps.toFixed(3)} fps`);
      }
    }

    return {
      transform: [{ rotate: `${x.value}deg` }],
    };
  });

  return (
    <View>
      <Animated.View
        style={[{ width: 200, height: 200, backgroundColor: 'red' }, styles]}
        onTouchStart={handlePress}
      />
    </View>
  );
}
```

**Comment by coder-xiaomo** [comment]
It does not seem to be optimized on Android until the current version of 0.73.5

I tried to create a new React Native project and run it on a real device, again up to 60fps

Anything new that can address this in the recent version?

**Pull request merged**
