### PR TITLE
[DRAFT] Layout Animations for Fabric

### PR DESCRIPTION
**Pull request by tomekzaw**
## Description

Work in progress.

### CODE REVIEW

**Comment by ali-io** [comment]
would this be built on top of #3332?

**Comment by tomekzaw** [comment]
> would this be built on top of https://github.com/software-mansion/react-native-reanimated/pull/3332?

Yes.

**Comment by angelo-hub** [comment]
Is this branch still on progress?

**Comment by anton-patrushev** [comment]
Can you prioritize this PR to be included into one of the upcoming releases?

**Comment by tomekzaw** [comment]
@anton-patrushev We're actively working on implementing Layout Animations for Fabric (on a separate branch).

**Comment by piaskowyk** [comment]
Since we have a proper implementation of Layout Animation for Fabric - https://github.com/software-mansion/react-native-reanimated/pull/6055, we can close this one 🫡

**Pull request closed without merging**
