### PR TITLE
Add example for Next.js

### PR DESCRIPTION
**Pull request by bartlomiejbloniarz**
## Summary

This PR adds an example with Next.js and a CI to test build fails. It is intended to prevent using api that is only available in a browser (w.g. window) without an appropriate check. This ensures that reanimated can be used with SSG.

## Test plan

Build the example with `yarn build` and start with `yarn start`. You can also start it in dev mode using `yarn dev` and check if it responds changes in reanimated core.

### CODE REVIEW

**Review by tjzel — CHANGES_REQUESTED** [review]
Requesting changes in blanco

**Comment by nandorojo** [comment]
FYI – the optimal setup for Next.js / web to confirm tree shaking would be to get rid of `shouldBeUseWeb()` which is used in many places in favor of platform-based files (`index.web.ts`). This would ensure what we aren't importing any unused variables or using conditional declarations for things in the wrong places. It would result in more files but be far more resilient and less prone to tree shaking regressions.

**Comment by bartlomiejbloniarz** [comment]
@nandorojo I am currently working on that in #5203

**Comment by nandorojo** [comment]
Awesome, glad to see this getting attention.

Just left some comments.

**Pull request merged**
