### PR TITLE
fix: fixed NullPointerException on Android 5.1

### PR DESCRIPTION
**Pull request by giautm**
## Description

Close https://github.com/software-mansion/react-native-reanimated/issues/2773

ADB log crash
```
W/System.err( 5236): java.lang.NoSuchFieldException: accessFlags
W/System.err( 5236): 	at java.lang.Class.getDeclaredField(Class.java:890)
W/System.err( 5236): 	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.<init>(ReanimatedNativeHierarchyManager.java:208)
W/System.err( 5236): 	at com.facebook.react.uimanager.ReanimatedUIImplementation.<init>(ReanimatedUIImplementation.java:40)
W/System.err( 5236): 	at com.facebook.react.uimanager.ReaUiImplementationProvider.createUIImplementation(ReanimatedUIManager.java:23)
W/System.err( 5236): 	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:189)
W/System.err( 5236): 	at com.facebook.react.uimanager.ReanimatedUIManager.<init>(ReanimatedUIManager.java:38)
W/System.err( 5236): 	at com.swmansion.reanimated.ReanimatedPackage.createUIManager(ReanimatedPackage.java:77)
W/System.err( 5236): 	at com.swmansion.reanimated.ReanimatedPackage.getModule(ReanimatedPackage.java:30)
W/System.err( 5236): 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
W/System.err( 5236): 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
W/System.err( 5236): 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
W/System.err( 5236): 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
W/System.err( 5236): 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149)
W/System.err( 5236): 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:488)
W/System.err( 5236): 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:464)
W/System.err( 5236): 	at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:165)
W/System.err( 5236): 	at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:157)
W/System.err( 5236): 	at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:99)
W/System.err( 5236): 	at com.swmansion.reanimated.EXReanimatedAdapter.registerJSIModules(EXReanimatedAdapter.java:9)
W/System.err( 5236): 	at expo.modules.adapters.reanimated.EXReanimatedPackage$1.onRegisterJSIModules(EXReanimatedPackage.java:21)
W/System.err( 5236): 	at expo.modules.ReactNativeHostWrapper$JSIModuleContainerPackage.getJSIModules(ReactNativeHostWrapper.kt:95)
W/System.err( 5236): 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1265)
W/System.err( 5236): 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
W/System.err( 5236): 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
W/System.err( 5236): 	at java.lang.Thread.run(Thread.java:818)
```
## Screenshots / GIFs

Screen Shot 2022-01-16 at 13 31 28

## Checklist

- [ ] Included code example that can be used to test this change
- [x] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [x] Ensured that CI passes

### CODE REVIEW

**Comment by giautm** [comment]
cc @piaskowyk

**Comment by piaskowyk** [comment]
Sorry for the bot 😄  We will argue outside the PR ⚔️

**Comment by giautm** [comment]
This commit https://github.com/software-mansion/react-native-reanimated/pull/2847/commits/60d94795a4deb446367243738b1bca2ac5d3cda0 is not related to the fix, but it makes CI build success. I can remove it if you want.

**Comment by kacperkapusciak** [comment]
> Sorry for the bot 😄 We (me and the bot) will argue outside the PR ⚔️

I think I've settled the dispute 😅

**Comment by giautm** [comment]
So, now we talk about this PR? Anything I need to updates?

**Comment by piaskowyk** [comment]
My changes are based on https://github.com/wix/Detox/pull/2922. They had a similar problem.

@giautm Could you check if it works for you?

**Comment by partiellkorrekt** [comment]
This pull-request fixes the following bug as well: https://github.com/software-mansion/react-native-reanimated/issues/2702

**Comment by giautm** [comment]
> My changes are based on https://github.com/wix/Detox/pull/2922. They had a similar problem.
> 
> 
> 
> @giautm Could you check if it works for you?

I think it will work. Not near a computer to verify it right now.

Please note that we need to updates for RN62 patch as well.

**Comment by piaskowyk** [comment]
Thanks for reminding me about RN62 🙌

**Comment by giautm** [comment]
By using [the build from my workflow](https://github.com/giautm/react-native-reanimated/actions/runs/1713641466), I can confirm this PR fixed crash in our apps. 👍

**Comment by partiellkorrekt** [comment]
I built this branch myself today and I can also confirm that it's working very well on Android 5 (and above). All of my animations are also working fine :)

**Comment by piaskowyk** [comment]
Thanks to everyone for the help! ❤️ I will publish this PR in the next release.

**Comment by sam-houle1** [comment]
Hi, I'm trying to use this PR inside my project, but I get an error when trying to ./gradlew clean inside android folder. The error is: `A problem occurred evaluating project ':react-native-reanimated'.
> /Users/macmini/Web/Activix/activix-crm-mobile/node_modules/react-native-reanimated/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)`

Im on react-native 0.66.4. I wonder if its a real problem with my react-native version or if I didn't setup the repo properly

Thanks for anyone who can help.

**Comment by partiellkorrekt** [comment]
@sam-houle1 I think you are trying to install the package directly from GitHub. But this package must be build first to be used inside a react-native project. You can download a build from the link in this comment: https://github.com/software-mansion/react-native-reanimated/pull/2847#issuecomment-1015662261

**Comment by TheMakerOleguch** [comment]
Do we have some ETA regarding new release with this change?

**Review by piaskowyk — APPROVED** [review]

**Comment by SaeedZhiany** [comment]
Thanks, @giautm and @piaskowyk 

Will we get this fix on a release version any soon?

**Comment by ilyausorov** [comment]
@piaskowyk Is there an ETA on when this will land in a next version? 2.3.2 hopefully soon?

**Comment by ht512512** [comment]
Currently expo 44 builds using the package are DOA on Android 5 because of this issue. It would be very very helpful to the community torelease this in a patch release soon. Please consider it. Thanks.

**Comment by abumalick** [comment]
It has been released in https://github.com/software-mansion/react-native-reanimated/releases/tag/2.4.0

**Pull request merged**
