### PR TITLE
Add 2048 example

### PR DESCRIPTION
**Pull request by tomekzaw**
## Summary

This PR adds [2048 game](https://en.wikipedia.org/wiki/2048_(video_game)) example.

https://github.com/software-mansion/react-native-reanimated/assets/20516055/db10f66c-707d-4442-959f-ee455fe62bd6

## Test plan

Just play the game.

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]
🤯2️⃣🐎0️⃣🐎4️⃣🐎8️⃣🤯

**Comment by tjzel** [comment]
Are the values added on the UI thread? 🤯

**Comment by tomekzaw** [comment]
> Are the values added on the UI thread? 🤯

Nope, they are added on the JS thread. Primarily, I wanted to use Layout Animations so I need React renders for that.

**Comment by tomekzaw** [comment]
TODO: fix bug that new tiles are added even though the rest of the board hasn't changed when swiping in the same direction multiple times

**Comment by mrousavy** [comment]
nice, I can play this on my flight to appjs

**Comment by tjzel** [comment]
Is the bug fixed? @bartlomiejbloniarz 🙏

**Comment by bartlomiejbloniarz** [comment]
@tjzel yes!

**Comment by piaskowyk** [comment]
So, can we merge it, or are we waiting for something?

**Pull request merged**
